export const quizQuestions = {
  questionsOne: [
    {
      type: 'single-choice',
      question: 'Cześć!',
      choices: ['Elsa', 'Terve', 'Tervetuloa', 'Onnea'],
      correctAnswer: 'Terve',
    },

    {
      type: 'create-sentence',
      question: 'Cześć! Kim jesteś? ',
      choices: [
        'Kuka',
        'mies',
        'sauna',
        'olet',
        'sinä',
        'Terve',
        'Onnea',
        'hän',
      ],
      correctAnswer: 'Terve kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Otso',
      choices: ['Terve', 'Onnea', 'Otso', 'olemee', 'Minä', 'olen'],
      correctAnswer: 'Minä olen Otso',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim jesteś?',
      choices: [
        'Anteeksi',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'tanssin',
        'Pari',
        'nyt',
        'todella',
      ],
      correctAnswer: 'Anteeksi kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Elsa',
      choices: [
        'Elsa',
        'Terve',
        'Tervetuloa',
        'Onnea',
        'Minä',
        'olemee',
        'olen',
      ],
      correctAnswer: 'Minä olen Elsa',
    },

    {
      type: 'single-choice',
      question: 'Witam!',
      choices: ['Terve', 'Tervetuloa', 'Onnea', 'Otso', 'olemee'],
      correctAnswer: 'Tervetuloa',
    },

    {
      type: 'create-sentence',
      question: 'Jej! Powodzenia!',
      choices: ['Anteeksi', 'Onnea', 'Sinä', 'olet', 'tanssin', 'Pari', 'Jee'],
      correctAnswer: 'Jee Onnea',
    },

    {
      type: 'create-sentence',
      question: 'Pyry, jesteś zabawny',
      choices: [
        'Onnea',
        'Pyry',
        'sinä',
        'olen',
        'olet',
        'lapsi',
        'hauska',
        'aina',
        'paljon',
      ],
      correctAnswer: 'Pyry sinä olet hauska',
    },

    {
      type: 'create-sentence',
      question: 'Kippis ja paljon onnea!',
      choices: [
        'Cześć',
        'Na',
        'zdrowie',
        'ja',
        'ona',
        'pije',
        'Witam',
        'powodzenia',
        'i',
      ],
      correctAnswer: 'Na zdrowie i powodzenia',
    },

    {
      type: 'create-sentence',
      question: 'Na zdrowie i powodzenia!',
      choices: [
        'ja',
        'Kippis',
        'lapsi',
        'väinö',
        'mies',
        'hauska',
        'onnea',
        'sinä',
        'olen',
        'paljon',
      ],
      correctAnswer: 'Kippis ja paljon onnea',
    },

    {
      type: 'single-choice',
      question: 'Nainen',
      choices: ['nie', 'mężczyzna', 'kobieta', 'dziecko', 'nie wiem'],
      correctAnswer: 'kobieta',
    },

    {
      type: 'create-sentence',
      question: 'Elsa on nainen',
      choices: ['Otso', 'ma', 'Elsa', 'dzieckiem', 'kobietą', 'nie', 'jest'],
      correctAnswer: 'Elsa jest kobietą',
    },

    {
      type: 'create-sentence',
      question: 'Kuba on mies',
      choices: [
        'miesiąc',
        'Kuba',
        'ma',
        'mężczyzną',
        'miejsce',
        'robi',
        'jest',
      ],
      correctAnswer: 'Kuba jest mężczyzną',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Otso',
      choices: [
        'Pyry',
        'Otso',
        'olemee',
        'olen',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'Minä',
      ],
      correctAnswer: 'Minä olen Otso',
    },

    {
      type: 'single-choice',
      question: 'Anteeksi',
      choices: ['Dziękuje', 'Przepraszam', 'Narazie', 'Cześć', 'Usiądź'],
      correctAnswer: 'Przepraszam',
    },

    {
      type: 'single-choice',
      question: 'Dziecko',
      choices: ['lapsi', 'väinö', 'mies', 'hauska', 'onnea', 'sinä'],
      correctAnswer: 'lapsi',
    },

    {
      type: 'create-sentence',
      question: 'Kuka hän on?',
      choices: ['Kim', 'Co', 'to', 'jest', 'Gdzie', 'ona', 'Jakie'],
      correctAnswer: 'Kim ona jest',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim ona jest?',
      choices: ['lapsi', 'kuka', 'on', 'Anteeksi', 'mies', 'hän', 'sinä'],
      correctAnswer: 'Anteeksi kuka hän on',
    },

    {
      type: 'single-choice',
      question: 'Mężczyzna',
      choices: ['nainen', 'paljon', 'tanssin', 'väinö', 'mies'],
      correctAnswer: 'mies',
    },

    {
      type: 'single-choice',
      question: 'przystojny',
      choices: ['kaunis', 'komea', 'kota', 'hauska', 'onnea', 'todella'],
      correctAnswer: 'komea',
    },

    {
      type: 'single-choice',
      question: 'Finlandia',
      choices: ['Fin', 'Pari', 'Suomi', 'Aina', 'Tervetuloa'],
      correctAnswer: 'Suomi',
    },

    {
      type: 'single-choice',
      question: 'Aina',
      choices: ['zabawny', 'pierwszy', 'znowu', 'zawsze', 'wiem'],
      correctAnswer: 'zawsze',
    },

    {
      type: 'create-sentence',
      question: 'Finlandia jest zawsze piękna',
      choices: [
        'nainen',
        'aina',
        'Anteeksi',
        'on',
        'kaunis',
        'Suomi',
        'todella',
        'sinä',
      ],
      correctAnswer: 'Suomi on aina kaunis',
    },

    {
      type: 'create-sentence',
      question: 'Sinä olet todella komea',
      choices: [
        'naprawde',
        'Witam',
        'Dziękuje',
        'przystojny',
        'piękna',
        'Jesteś',
        'pije',
      ],
      correctAnswer: 'Jesteś naprawde przystojny',
    },

    {
      type: 'single-choice',
      question: 'Cześć!',
      choices: ['Elsa', 'Terve', 'Tervetuloa', 'Onnea'],
      correctAnswer: 'Terve',
    },

    {
      type: 'single-choice',
      question: 'Dziecko',
      choices: ['lapsi', 'väinö', 'mies', 'hauska', 'onnea', 'sinä'],
      correctAnswer: 'lapsi',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Elsa',
      choices: [
        'Elsa',
        'Terve',
        'Tervetuloa',
        'Onnea',
        'Minä',
        'olemee',
        'olen',
      ],
      correctAnswer: 'Minä olen Elsa',
    },

    {
      type: 'create-sentence',
      question: 'Cześć! Kim jesteś? ',
      choices: [
        'Kuka',
        'mies',
        'sauna',
        'olet',
        'sinä',
        'Terve',
        'Onnea',
        'hän',
      ],
      correctAnswer: 'Terve kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim ona jest?',
      choices: ['lapsi', 'kuka', 'on', 'Anteeksi', 'mies', 'hän', 'sinä'],
      correctAnswer: 'Anteeksi kuka hän on',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim jesteś?',
      choices: [
        'Anteeksi',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'tanssin',
        'Pari',
        'nyt',
        'todella',
      ],
      correctAnswer: 'Anteeksi kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Finlandia jest zawsze piękna',
      choices: [
        'nainen',
        'aina',
        'Anteeksi',
        'on',
        'kaunis',
        'Suomi',
        'todella',
        'sinä',
      ],
      correctAnswer: 'Suomi on aina kaunis',
    },

    {
      type: 'single-choice',
      question: 'Mężczyzna',
      choices: ['nainen', 'paljon', 'tanssin', 'väinö', 'mies'],
      correctAnswer: 'mies',
    },

    {
      type: 'single-choice',
      question: 'przystojny',
      choices: ['kaunis', 'komea', 'kota', 'hauska', 'onnea', 'todella'],
      correctAnswer: 'komea',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Otso',
      choices: [
        'Pyry',
        'Otso',
        'olemee',
        'olen',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'Minä',
      ],
      correctAnswer: 'Minä olen Otso',
    },

    {
      type: 'single-choice',
      question: 'Anteeksi',
      choices: ['Dziękuje', 'Przepraszam', 'Narazie', 'Cześć', 'Usiądź'],
      correctAnswer: 'Przepraszam',
    },

    {
      type: 'single-choice',
      question: 'Nainen',
      choices: ['nie', 'mężczyzna', 'kobieta', 'dziecko', 'nie wiem'],
      correctAnswer: 'kobieta',
    },

    {
      type: 'create-sentence',
      question: 'Pyry, jesteś zabawny',
      choices: [
        'Onnea',
        'Pyry',
        'sinä',
        'olen',
        'olet',
        'lapsi',
        'hauska',
        'aina',
        'paljon',
      ],
      correctAnswer: 'Pyry sinä olet hauska',
    },

    {
      type: 'create-sentence',
      question: 'Kippis ja paljon onnea!',
      choices: [
        'Cześć',
        'Na',
        'zdrowie',
        'ja',
        'ona',
        'pije',
        'Witam',
        'powodzenia',
        'i',
      ],
      correctAnswer: 'Na zdrowie i powodzenia',
    },

    {
      type: 'single-choice',
      question: 'Witam!',
      choices: ['Terve', 'Tervetuloa', 'Onnea', 'Otso', 'olemee'],
      correctAnswer: 'Tervetuloa',
    },

    {
      type: 'create-sentence',
      question: 'Jej! Powodzenia!',
      choices: ['Anteeksi', 'Onnea', 'Sinä', 'olet', 'tanssin', 'Pari', 'Jee'],
      correctAnswer: 'Jee Onnea',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Elsa',
      choices: [
        'Elsa',
        'Terve',
        'Tervetuloa',
        'Onnea',
        'Minä',
        'olemee',
        'olen',
      ],
      correctAnswer: 'Minä olen Elsa',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim jesteś?',
      choices: [
        'Anteeksi',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'tanssin',
        'Pari',
        'nyt',
        'todella',
      ],
      correctAnswer: 'Anteeksi kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Finlandia jest zawsze piękna',
      choices: [
        'nainen',
        'aina',
        'Anteeksi',
        'on',
        'kaunis',
        'Suomi',
        'todella',
        'sinä',
      ],
      correctAnswer: 'Suomi on aina kaunis',
    },

    {
      type: 'single-choice',
      question: 'Cześć!',
      choices: ['Elsa', 'Terve', 'Tervetuloa', 'Onnea'],
      correctAnswer: 'Terve',
    },

    {
      type: 'create-sentence',
      question: 'Cześć! Kim jesteś?',
      choices: [
        'Kuka',
        'mies',
        'sauna',
        'olet',
        'sinä',
        'Terve',
        'Onnea',
        'hän',
      ],
      correctAnswer: 'Terve kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Otso',
      choices: ['Terve', 'Onnea', 'Otso', 'olemee', 'Minä', 'olen'],
      correctAnswer: 'Minä olen Otso',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim jesteś?',
      choices: [
        'Anteeksi',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'tanssin',
        'Pari',
        'nyt',
        'todella',
      ],
      correctAnswer: 'Anteeksi kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Elsa',
      choices: [
        'Elsa',
        'Terve',
        'Tervetuloa',
        'Onnea',
        'Minä',
        'olemee',
        'olen',
      ],
      correctAnswer: 'Minä olen Elsa',
    },

    {
      type: 'single-choice',
      question: 'Witam!',
      choices: ['Terve', 'Tervetuloa', 'Onnea', 'Otso', 'olemee'],
      correctAnswer: 'Tervetuloa',
    },

    {
      type: 'create-sentence',
      question: 'Jej! Powodzenia!',
      choices: ['Anteeksi', 'Onnea', 'Sinä', 'olet', 'tanssin', 'Pari', 'Jee'],
      correctAnswer: 'Jee Onnea',
    },

    {
      type: 'create-sentence',
      question: 'Pyry, jesteś zabawny',
      choices: [
        'Onnea',
        'Pyry',
        'sinä',
        'olen',
        'olet',
        'lapsi',
        'hauska',
        'aina',
        'paljon',
      ],
      correctAnswer: 'Pyry sinä olet hauska',
    },

    {
      type: 'create-sentence',
      question: 'Kippis ja paljon onnea!',
      choices: [
        'Cześć',
        'Na',
        'Zdrowie',
        'ja',
        'ona',
        'pije',
        'Witam',
        'powodzenia',
        'i',
      ],
      correctAnswer: 'Na zdrowie i powodzenia',
    },

    {
      type: 'create-sentence',
      question: 'Na zdrowie i powodzenia!',
      choices: [
        'ja',
        'Kippis',
        'lapsi',
        'väinö',
        'mies',
        'hauska',
        'onnea',
        'sinä',
        'olen',
        'paljon',
      ],
      correctAnswer: 'Kippis ja paljon onnea',
    },

    {
      type: 'single-choice',
      question: 'Nainen',
      choices: ['nie', 'mężczyzna', 'kobieta', 'dziecko', 'nie wiem'],
      correctAnswer: 'kobieta',
    },

    {
      type: 'create-sentence',
      question: 'Elsa on nainen',
      choices: ['Otso', 'ma', 'Elsa', 'dzieckiem', 'kobietą', 'nie', 'jest'],
      correctAnswer: 'Elsa jest kobietą',
    },

    {
      type: 'create-sentence',
      question: 'Kuba on mies',
      choices: [
        'miesiąc',
        'Kuba',
        'ma',
        'mężczyzną',
        'miejsce',
        'robi',
        'jest',
      ],
      correctAnswer: 'Kuba jest mężczyzną',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Otso',
      choices: [
        'Pyry',
        'Otso',
        'olemee',
        'olen',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'Minä',
      ],
      correctAnswer: 'Minä olen Otso',
    },

    {
      type: 'single-choice',
      question: 'Anteeksi',
      choices: ['Dziękuje', 'Przepraszam', 'Narazie', 'Cześć', 'Usiądź'],
      correctAnswer: 'Przepraszam',
    },

    {
      type: 'single-choice',
      question: 'Dziecko',
      choices: ['lapsi', 'väinö', 'mies', 'hauska', 'onnea', 'sinä'],
      correctAnswer: 'lapsi',
    },

    {
      type: 'create-sentence',
      question: 'Kuka hän on?',
      choices: ['Kim', 'Co', 'to', 'jest', 'Gdzie', 'ona', 'Jakie'],
      correctAnswer: 'Kim ona jest',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim ona jest?',
      choices: ['lapsi', 'kuka', 'on', 'Anteeksi', 'mies', 'hän', 'sinä'],
      correctAnswer: 'Anteeksi kuka hän on',
    },

    {
      type: 'single-choice',
      question: 'Mężczyzna',
      choices: ['nainen', 'paljon', 'tanssin', 'väinö', 'mies'],
      correctAnswer: 'mies',
    },

    {
      type: 'single-choice',
      question: 'przystojny',
      choices: ['kaunis', 'komea', 'kota', 'hauska', 'onnea', 'todella'],
      correctAnswer: 'komea',
    },

    {
      type: 'single-choice',
      question: 'Finlandia',
      choices: ['Fin', 'Pari', 'Suomi', 'Aina', 'Tervetuloa'],
      correctAnswer: 'Suomi',
    },

    {
      type: 'single-choice',
      question: 'Aina',
      choices: ['zabawny', 'pierwszy', 'znowu', 'zawsze', 'wiem'],
      correctAnswer: 'zawsze',
    },

    {
      type: 'create-sentence',
      question: 'Finlandia jest zawsze piękna',
      choices: [
        'nainen',
        'aina',
        'Anteeksi',
        'on',
        'kaunis',
        'Suomi',
        'todella',
        'sinä',
      ],
      correctAnswer: 'Suomi on aina kaunis',
    },

    {
      type: 'create-sentence',
      question: 'Sinä olet todella komea',
      choices: [
        'naprawde',
        'Witam',
        'Dziękuje',
        'przystojny',
        'piękna',
        'Jesteś',
        'pije',
      ],
      correctAnswer: 'Jesteś naprawde przystojny',
    },

    {
      type: 'single-choice',
      question: 'Cześć!',
      choices: ['Elsa', 'Terve', 'Tervetuloa', 'Onnea'],
      correctAnswer: 'Terve',
    },

    {
      type: 'single-choice',
      question: 'Dziecko',
      choices: ['lapsi', 'väinö', 'mies', 'hauska', 'onnea', 'sinä'],
      correctAnswer: 'lapsi',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Elsa',
      choices: [
        'Elsa',
        'Terve',
        'Tervetuloa',
        'Onnea',
        'Minä',
        'olemee',
        'olen',
      ],
      correctAnswer: 'Minä olen Elsa',
    },

    {
      type: 'create-sentence',
      question: 'Cześć! Kim jesteś? ',
      choices: [
        'Kuka',
        'mies',
        'sauna',
        'olet',
        'sinä',
        'Terve',
        'Onnea',
        'hän',
      ],
      correctAnswer: 'Terve kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim ona jest?',
      choices: ['lapsi', 'kuka', 'on', 'Anteeksi', 'mies', 'hän', 'sinä'],
      correctAnswer: 'Anteeksi kuka hän on',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim jesteś?',
      choices: [
        'Anteeksi',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'tanssin',
        'Pari',
        'nyt',
        'todella',
      ],
      correctAnswer: 'Anteeksi kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Finlandia jest zawsze piękna',
      choices: [
        'nainen',
        'aina',
        'Anteeksi',
        'on',
        'kaunis',
        'Suomi',
        'todella',
        'sinä',
      ],
      correctAnswer: 'Suomi on aina kaunis',
    },

    {
      type: 'single-choice',
      question: 'Mężczyzna',
      choices: ['nainen', 'paljon', 'tanssin', 'väinö', 'mies'],
      correctAnswer: 'mies',
    },

    {
      type: 'single-choice',
      question: 'przystojny',
      choices: ['kaunis', 'komea', 'kota', 'hauska', 'onnea', 'todella'],
      correctAnswer: 'komea',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Otso',
      choices: [
        'Pyry',
        'Otso',
        'olemee',
        'olen',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'Minä',
      ],
      correctAnswer: 'Minä olen Otso',
    },

    {
      type: 'single-choice',
      question: 'Anteeksi',
      choices: ['Dziękuje', 'Przepraszam', 'Narazie', 'Cześć', 'Usiądź'],
      correctAnswer: 'Przepraszam',
    },

    {
      type: 'single-choice',
      question: 'Nainen',
      choices: ['nie', 'mężczyzna', 'kobieta', 'dziecko', 'nie wiem'],
      correctAnswer: 'kobieta',
    },

    {
      type: 'create-sentence',
      question: 'Pyry, jesteś zabawny',
      choices: [
        'Onnea',
        'Pyry',
        'sinä',
        'olen',
        'olet',
        'lapsi',
        'hauska',
        'aina',
        'paljon',
      ],
      correctAnswer: 'Pyry sinä olet hauska',
    },

    {
      type: 'create-sentence',
      question: 'Kippis ja paljon onnea!',
      choices: [
        'Cześć',
        'Na',
        'zdrowie',
        'ja',
        'ona',
        'pije',
        'Witam',
        'powodzenia',
        'i',
      ],
      correctAnswer: 'Na zdrowie i powodzenia',
    },

    {
      type: 'single-choice',
      question: 'Witam!',
      choices: ['Terve', 'Tervetuloa', 'Onnea', 'Otso', 'olemee'],
      correctAnswer: 'Tervetuloa',
    },

    {
      type: 'create-sentence',
      question: 'Jej! Powodzenia!',
      choices: ['Anteeksi', 'Onnea', 'Sinä', 'olet', 'tanssin', 'Pari', 'Jee'],
      correctAnswer: 'Jee Onnea',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Elsa',
      choices: [
        'Elsa',
        'Terve',
        'Tervetuloa',
        'Onnea',
        'Minä',
        'olemee',
        'olen',
      ],
      correctAnswer: 'Minä olen Elsa',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim jesteś?',
      choices: [
        'Anteeksi',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'tanssin',
        'Pari',
        'nyt',
        'todella',
      ],
      correctAnswer: 'Anteeksi kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Finlandia jest zawsze piękna',
      choices: [
        'nainen',
        'aina',
        'Anteeksi',
        'on',
        'kaunis',
        'Suomi',
        'todella',
        'sinä',
      ],
      correctAnswer: 'Suomi on aina kaunis',
    },
  ],

  questionsTwo: [
    {
      type: 'create-sentence',
      question: 'To jest dobra sauna',
      choices: [
        'hyvä',
        'han',
        'ja',
        'sauna',
        'on',
        'Olet',
        'tyttö',
        'Onko',
        'Tämä',
      ],
      correctAnswer: 'Tämä on hyvä sauna',
    },

    {
      type: 'single-choice',
      question: 'pies',
      choices: ['kaunis', 'kiltti', 'olemee', 'koira', 'aina', 'mies', 'lapsi'],
      correctAnswer: 'koira',
    },

    {
      type: 'single-choice',
      question: 'cicha',
      choices: [
        'olmee',
        'hiljainen',
        'poika',
        'aina',
        'rehellinen',
        'lapsi',
        'maa',
      ],
      correctAnswer: 'hiljainen',
    },

    {
      type: 'create-sentence',
      question: 'Tämä on hyvä sauna',
      choices: [
        'Ona',
        'ma',
        'jest',
        'To',
        'sauna',
        'zła',
        'zawsze',
        'pierwszy',
        'dobra',
      ],
      correctAnswer: 'To jest dobra sauna',
    },

    {
      type: 'create-sentence',
      question: 'Hilla on hiljainen tyttö',
      choices: [
        'ona',
        'jest',
        'piękną',
        'wiem',
        'Hilla',
        'dzieckiem',
        'dziewczyną',
        'cichą',
      ],
      correctAnswer: 'Hilla jest cichą dziewczyną',
    },

    {
      type: 'create-sentence',
      question: 'Jesteś dobrą dziewczyną',
      choices: [
        'mukava',
        'aina',
        'kuka',
        'Olet',
        'tyttö',
        'tuhma',
        'olemee',
        'poika',
      ],
      correctAnswer: 'Olet mukava tyttö',
    },

    {
      type: 'create-sentence',
      question: 'Olet rehellinen nainen',
      choices: [
        'Ona',
        'jest',
        'Jesteś',
        'kobietą',
        'miłą',
        'szczerą',
        'piękną',
      ],
      correctAnswer: 'Jesteś szczerą kobietą',
    },

    {
      type: 'single-choice',
      question: 'szczery',
      choices: [
        'olmee',
        'tanssin',
        'poika',
        'aina',
        'rehellinen',
        'lapsi',
        'maa',
      ],
      correctAnswer: 'rehellinen',
    },

    {
      type: 'create-sentence',
      question: 'Estonia jest mała i piękna',
      choices: [
        'Pari',
        'ja',
        'on',
        'kaunis',
        'kiltti',
        'aina',
        'Viro',
        'pieni',
        'olen',
        'poika',
        'rehellinen',
      ],
      correctAnswer: 'Viro on pieni ja kaunis',
    },

    {
      type: 'single-choice',
      question: 'dziewczyna',
      choices: ['poika', 'aina', 'kuka', 'olen', 'tyttö', 'tuhma', 'olemee'],
      correctAnswer: 'tyttö',
    },

    {
      type: 'create-sentence',
      question: 'Jakiego rodzaju to jest pies?',
      choices: [
        'Tervetuloa',
        'olmee',
        'koira',
        'se',
        'tanssin',
        'poika',
        'aina',
        'on',
        'lapsi',
        'maa',
        'Millainen',
      ],
      correctAnswer: 'Millainen koira se on',
    },

    {
      type: 'create-sentence',
      question: 'Jesteś dobrym chłopakiem',
      choices: [
        'mukava',
        'aina',
        'kuka',
        'Olet',
        'tyttö',
        'tuhma',
        'olemee',
        'poika',
      ],
      correctAnswer: 'Olet mukava poika',
    },

    {
      type: 'single-choice',
      question: 'zajączek',
      choices: ['kaunis', 'kiltti', 'pupu', 'koira', 'aina', 'mies', 'lapsi'],
      correctAnswer: 'pupu',
    },

    {
      type: 'create-sentence',
      question: 'Ja mam zajączka',
      choices: [
        'Pari',
        'pupu',
        'olen',
        'ja',
        'on',
        'Millainen',
        'Minulla',
        'pieni',
      ],
      correctAnswer: 'Minulla on pupu',
    },

    {
      type: 'create-sentence',
      question: 'To jest małe i miłe',
      choices: [
        'Olet',
        'Se',
        'ja',
        'kaunis',
        'kiltti',
        'tanssin',
        'pieni',
        'on',
        'aina',
      ],
      correctAnswer: 'Se on pieni ja kiltti',
    },

    {
      type: 'create-sentence',
      question: 'Se on pieni ja kiltti',
      choices: [
        'miłe',
        'ty',
        'piękne',
        'szczere',
        'To',
        'Ten',
        'jest',
        'i',
        'małe',
        'znowu',
        'mam',
      ],
      correctAnswer: 'To jest małe i miłe',
    },

    {
      type: 'single-choice',
      question: 'niegrzeczny',
      choices: [
        'olmee',
        'tanssin',
        'poika',
        'aina',
        'rehellinen',
        'maa',
        'tuhma',
      ],
      correctAnswer: 'tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Ten kot jest niegrzeczny!',
      choices: [
        'Tämä',
        'kiltti',
        'tuhma',
        'ty',
        'ja',
        'Aina',
        'kissa',
        'aina',
        'Terve',
        'on',
      ],
      correctAnswer: 'Tämä kissa on tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Hänellä on sininen käärme',
      choices: [
        'kot',
        'Dziecko',
        'czerwonego',
        'zajączka',
        'węża',
        'ma',
        'nie ma',
        'niebieskiego',
        'Ona',
      ],
      correctAnswer: 'Ona ma niebieskiego węża',
    },

    {
      type: 'single-choice',
      question: 'sininen',
      choices: [
        'niebieski',
        'czerwony',
        'żółty',
        'zielony',
        'brązowy',
        'czarny',
      ],
      correctAnswer: 'niebieski',
    },

    {
      type: 'single-choice',
      question: 'Estonia',
      choices: ['Estonia', 'Estania', 'Suomi', 'Pari', 'Viro', 'Ruotsi'],
      correctAnswer: 'Viro',
    },

    {
      type: 'create-sentence',
      question: 'Jakim krajem jest Estonia',
      choices: [
        'Tervetuloa',
        'Minulla',
        'ja',
        'to',
        'Millainen',
        'maa',
        'Viro',
        'on',
        'aina',
        'han',
        'hän',
      ],
      correctAnswer: 'Millainen maa Viro on?',
    },

    {
      type: 'create-sentence',
      question: 'Viro on pieni ja kaunis',
      choices: [
        'Szwecja',
        'Finlandia',
        'piękna',
        'była',
        'jest',
        'też',
        'zawsze',
        'i',
        'mała',
        'Estonia',
      ],
      correctAnswer: 'Estonia jest mała i piękna',
    },

    {
      type: 'create-sentence',
      question: 'Czy Szwecja jest zimnym krajem?',
      choices: [
        'Ruotsi',
        'Suomi',
        'paljon',
        'kaunis',
        'kylmä',
        'maa',
        'ma',
        'Olet',
        'Onko',
        'tanssin',
        'rehellinen',
      ],
      correctAnswer: 'Onko Ruotsi kylmä maa',
    },

    {
      type: 'single-choice',
      question: 'Ruotsi',
      choices: [
        'Estonia',
        'wiem',
        'wąż',
        'pies',
        'kobieta',
        'Szwecja',
        'Polska',
        'dziecko',
      ],
      correctAnswer: 'Szwecja',
    },

    {
      type: 'create-sentence',
      question: 'Millainen koira se on?',
      choices: [
        'Jakiego',
        'Jakim',
        'pies',
        'robi',
        'Kto',
        'jest',
        'on',
        'to',
        'rodzaju',
      ],
      correctAnswer: 'Jakiego rodzaju to jest pies',
    },

    {
      type: 'create-sentence',
      question: 'To jest dobra sauna',
      choices: [
        'hyvä',
        'han',
        'ja',
        'sauna',
        'on',
        'Olet',
        'tyttö',
        'Onko',
        'Tämä',
      ],
      correctAnswer: 'Tämä on hyvä sauna',
    },

    {
      type: 'single-choice',
      question: 'pies',
      choices: ['kaunis', 'kiltti', 'olemee', 'koira', 'aina', 'mies', 'lapsi'],
      correctAnswer: 'koira',
    },

    {
      type: 'single-choice',
      question: 'cicha',
      choices: [
        'olmee',
        'hiljainen',
        'poika',
        'aina',
        'rehellinen',
        'lapsi',
        'maa',
      ],
      correctAnswer: 'hiljainen',
    },

    {
      type: 'create-sentence',
      question: 'Tämä on hyvä sauna',
      choices: [
        'Ona',
        'ma',
        'jest',
        'To',
        'sauna',
        'zła',
        'zawsze',
        'pierwszy',
        'dobra',
      ],
      correctAnswer: 'To jest dobra sauna',
    },

    {
      type: 'create-sentence',
      question: 'Hilla on hiljainen tyttö',
      choices: [
        'ona',
        'jest',
        'piękną',
        'wiem',
        'Hilla',
        'dzieckiem',
        'dziewczyną',
        'cichą',
      ],
      correctAnswer: 'Hilla jest cichą dziewczyną',
    },

    {
      type: 'create-sentence',
      question: 'Jesteś dobrą dziewczyną',
      choices: [
        'mukava',
        'aina',
        'kuka',
        'Olet',
        'tyttö',
        'tuhma',
        'olemee',
        'poika',
      ],
      correctAnswer: 'Olet mukava tyttö',
    },

    {
      type: 'create-sentence',
      question: 'Olet rehellinen nainen',
      choices: [
        'Ona',
        'jest',
        'Jesteś',
        'kobietą',
        'miłą',
        'szczerą',
        'piękną',
      ],
      correctAnswer: 'Jesteś szczerą kobietą',
    },

    {
      type: 'single-choice',
      question: 'szczery',
      choices: [
        'olmee',
        'tanssin',
        'poika',
        'aina',
        'rehellinen',
        'lapsi',
        'maa',
      ],
      correctAnswer: 'rehellinen',
    },

    {
      type: 'create-sentence',
      question: 'Estonia jest mała i piękna',
      choices: [
        'Pari',
        'ja',
        'on',
        'kaunis',
        'kiltti',
        'aina',
        'Viro',
        'pieni',
        'olen',
        'poika',
        'rehellinen',
      ],
      correctAnswer: 'Viro on pieni ja kaunis',
    },

    {
      type: 'single-choice',
      question: 'dziewczyna',
      choices: [
        'poika',
        'aina',
        'kuka',
        'olen',
        'tyttö',
        'tuhma',
        'olemee',
        'mukava',
      ],
      correctAnswer: 'tyttö',
    },

    {
      type: 'create-sentence',
      question: 'Jakiego rodzaju to jest pies?',
      choices: [
        'Tervetuloa',
        'olmee',
        'koira',
        'se',
        'tanssin',
        'poika',
        'aina',
        'on',
        'lapsi',
        'maa',
        'Millainen',
      ],
      correctAnswer: 'Millainen koira se on',
    },

    {
      type: 'create-sentence',
      question: 'Jesteś dobrym chłopakiem',
      choices: [
        'mukava',
        'aina',
        'kuka',
        'Olet',
        'tyttö',
        'tuhma',
        'olemee',
        'poika',
      ],
      correctAnswer: 'Olet mukava poika',
    },

    {
      type: 'single-choice',
      question: 'zajączek',
      choices: ['kaunis', 'kiltti', 'pupu', 'koira', 'aina', 'mies', 'lapsi'],
      correctAnswer: 'pupu',
    },

    {
      type: 'create-sentence',
      question: 'Ja mam zajączka',
      choices: [
        'Pari',
        'pupu',
        'olen',
        'ja',
        'on',
        'Millainen',
        'Minulla',
        'pieni',
      ],
      correctAnswer: 'Minulla on pupu',
    },

    {
      type: 'create-sentence',
      question: 'To jest małe i miłe',
      choices: [
        'Olet',
        'Se',
        'ja',
        'kaunis',
        'kiltti',
        'tanssin',
        'pieni',
        'on',
        'aina',
      ],
      correctAnswer: 'Se on pieni ja kiltti',
    },

    {
      type: 'create-sentence',
      question: 'Se on pieni ja kiltti',
      choices: [
        'miłe',
        'ty',
        'piękne',
        'szczere',
        'To',
        'Ten',
        'jest',
        'i',
        'małe',
        'znowu',
        'mam',
      ],
      correctAnswer: 'To jest małe i miłe',
    },

    {
      type: 'single-choice',
      question: 'niegrzeczny',
      choices: [
        'olmee',
        'tanssin',
        'poika',
        'aina',
        'rehellinen',
        'maa',
        'tuhma',
      ],
      correctAnswer: 'tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Ten kot jest niegrzeczny!',
      choices: [
        'Tämä',
        'kiltti',
        'tuhma',
        'ty',
        'ja',
        'Aina',
        'kissa',
        'aina',
        'Terve',
        'on',
      ],
      correctAnswer: 'Tämä kissa on tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Hänellä on sininen käärme',
      choices: [
        'kot',
        'Dziecko',
        'czerwonego',
        'zajączka',
        'węża',
        'ma',
        'nie ma',
        'niebieskiego',
        'Ona',
      ],
      correctAnswer: 'Ona ma niebieskiego węża',
    },

    {
      type: 'single-choice',
      question: 'sininen',
      choices: [
        'niebieski',
        'czerwony',
        'żółty',
        'zielony',
        'brązowy',
        'czarny',
      ],
      correctAnswer: 'niebieski',
    },

    {
      type: 'single-choice',
      question: 'Estonia',
      choices: ['Estonia', 'Estania', 'Suomi', 'Pari', 'Viro', 'Ruotsi'],
      correctAnswer: 'Viro',
    },

    {
      type: 'create-sentence',
      question: 'Jakim krajem jest Estonia',
      choices: [
        'Tervetuloa',
        'Minulla',
        'ja',
        'to',
        'Millainen',
        'maa',
        'Viro',
        'on',
        'aina',
        'han',
        'hän',
      ],
      correctAnswer: 'Millainen maa Viro on?',
    },

    {
      type: 'create-sentence',
      question: 'Viro on pieni ja kaunis',
      choices: [
        'Szwecja',
        'Finlandia',
        'piękna',
        'była',
        'jest',
        'też',
        'zawsze',
        'i',
        'mała',
        'Estonia',
      ],
      correctAnswer: 'Estonia jest mała i piękna',
    },

    {
      type: 'create-sentence',
      question: 'Czy Szwecja jest zimnym krajem?',
      choices: [
        'Ruotsi',
        'Suomi',
        'paljon',
        'kaunis',
        'kylmä',
        'maa',
        'ma',
        'Olet',
        'Onko',
        'tanssin',
        'rehellinen',
      ],
      correctAnswer: 'Onko Ruotsi kylmä maa',
    },

    {
      type: 'single-choice',
      question: 'Ruotsi',
      choices: [
        'Estonia',
        'wiem',
        'wąż',
        'pies',
        'kobieta',
        'Szwecja',
        'Polska',
        'dziecko',
      ],
      correctAnswer: 'Szwecja',
    },

    {
      type: 'create-sentence',
      question: 'Millainen koira se on?',
      choices: [
        'Jakiego',
        'Jakim',
        'pies',
        'robi',
        'Kto',
        'jest',
        'on',
        'to',
        'rodzaju',
      ],
      correctAnswer: 'Jakiego rodzaju to jest pies',
    },

    {
      type: 'create-sentence',
      question: 'Ja mam zajączka',
      choices: [
        'Pari',
        'pupu',
        'olen',
        'ja',
        'on',
        'Millainen',
        'Minulla',
        'pieni',
      ],
      correctAnswer: 'Minulla on pupu',
    },

    {
      type: 'create-sentence',
      question: 'To jest małe i miłe',
      choices: [
        'Olet',
        'Se',
        'ja',
        'kaunis',
        'kiltti',
        'tanssin',
        'pieni',
        'on',
        'aina',
      ],
      correctAnswer: 'Se on pieni ja kiltti',
    },

    {
      type: 'create-sentence',
      question: 'Se on pieni ja kiltti',
      choices: [
        'miłe',
        'ty',
        'piękne',
        'szczere',
        'To',
        'Ten',
        'jest',
        'i',
        'małe',
        'znowu',
        'mam',
      ],
      correctAnswer: 'To jest małe i miłe',
    },

    {
      type: 'single-choice',
      question: 'niegrzeczny',
      choices: [
        'olmee',
        'tanssin',
        'poika',
        'aina',
        'rehellinen',
        'maa',
        'tuhma',
      ],
      correctAnswer: 'tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Ten kot jest niegrzeczny!',
      choices: [
        'Tämä',
        'kiltti',
        'tuhma',
        'ty',
        'ja',
        'Aina',
        'kissa',
        'aina',
        'Terve',
        'on',
      ],
      correctAnswer: 'Tämä kissa on tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Hänellä on sininen käärme',
      choices: [
        'kot',
        'Dziecko',
        'czerwonego',
        'zajączka',
        'węża',
        'ma',
        'nie ma',
        'niebieskiego',
        'Ona',
      ],
      correctAnswer: 'Ona ma niebieskiego węża',
    },

    {
      type: 'single-choice',
      question: 'sininen',
      choices: [
        'niebieski',
        'czerwony',
        'żółty',
        'zielony',
        'brązowy',
        'czarny',
      ],
      correctAnswer: 'niebieski',
    },

    {
      type: 'single-choice',
      question: 'Estonia',
      choices: ['Estonia', 'Estania', 'Suomi', 'Pari', 'Viro', 'Ruotsi'],
      correctAnswer: 'Viro',
    },

    {
      type: 'create-sentence',
      question: 'Jakim krajem jest Estonia',
      choices: [
        'Tervetuloa',
        'Minulla',
        'ja',
        'to',
        'Millainen',
        'maa',
        'Viro',
        'on',
        'aina',
        'han',
        'hän',
      ],
      correctAnswer: 'Millainen maa Viro on?',
    },

    {
      type: 'create-sentence',
      question: 'Viro on pieni ja kaunis',
      choices: [
        'Szwecja',
        'Finlandia',
        'piękna',
        'była',
        'jest',
        'też',
        'zawsze',
        'i',
        'mała',
        'Estonia',
      ],
      correctAnswer: 'Estonia jest mała i piękna',
    },

    {
      type: 'create-sentence',
      question: 'Czy Szwecja jest zimnym krajem?',
      choices: [
        'Ruotsi',
        'Suomi',
        'paljon',
        'kaunis',
        'kylmä',
        'maa',
        'ma',
        'Olet',
        'Onko',
        'tanssin',
        'rehellinen',
      ],
      correctAnswer: 'Onko Ruotsi kylmä maa',
    },

    {
      type: 'single-choice',
      question: 'Ruotsi',
      choices: [
        'Estonia',
        'wiem',
        'wąż',
        'pies',
        'kobieta',
        'Szwecja',
        'Polska',
        'dziecko',
      ],
      correctAnswer: 'Szwecja',
    },

    {
      type: 'create-sentence',
      question: 'Millainen koira se on?',
      choices: [
        'Jakiego',
        'Jakim',
        'pies',
        'robi',
        'Kto',
        'jest',
        'on',
        'to',
        'rodzaju',
      ],
      correctAnswer: 'Jakiego rodzaju to jest pies',
    },

    {
      type: 'create-sentence',
      question: 'To jest dobra sauna',
      choices: [
        'hyvä',
        'han',
        'ja',
        'sauna',
        'on',
        'Olet',
        'tyttö',
        'Onko',
        'Tämä',
      ],
      correctAnswer: 'Tämä on hyvä sauna',
    },

    {
      type: 'single-choice',
      question: 'pies',
      choices: ['kaunis', 'kiltti', 'olemee', 'koira', 'aina', 'mies', 'lapsi'],
      correctAnswer: 'koira',
    },

    {
      type: 'single-choice',
      question: 'cicha',
      choices: [
        'olmee',
        'hiljainen',
        'poika',
        'aina',
        'rehellinen',
        'lapsi',
        'maa',
      ],
      correctAnswer: 'hiljainen',
    },

    {
      type: 'create-sentence',
      question: 'Tämä on hyvä sauna',
      choices: [
        'Ona',
        'ma',
        'jest',
        'To',
        'sauna',
        'zła',
        'zawsze',
        'pierwszy',
        'dobra',
      ],
      correctAnswer: 'To jest dobra sauna',
    },

    {
      type: 'create-sentence',
      question: 'Hilla on hiljainen tyttö',
      choices: [
        'ona',
        'jest',
        'piękną',
        'wiem',
        'Hilla',
        'dzieckiem',
        'dziewczyną',
        'cichą',
      ],
      correctAnswer: 'Hilla jest cichą dziewczyną',
    },

    {
      type: 'create-sentence',
      question: 'Jesteś dobrą dziewczyną',
      choices: [
        'mukava',
        'aina',
        'kuka',
        'Olet',
        'tyttö',
        'tuhma',
        'olemee',
        'poika',
      ],
      correctAnswer: 'Olet mukava tyttö',
    },

    {
      type: 'create-sentence',
      question: 'Olet rehellinen nainen',
      choices: [
        'Ona',
        'jest',
        'Jesteś',
        'kobietą',
        'miłą',
        'szczerą',
        'piękną',
      ],
      correctAnswer: 'Jesteś szczerą kobietą',
    },

    {
      type: 'single-choice',
      question: 'szczery',
      choices: [
        'olmee',
        'tanssin',
        'poika',
        'aina',
        'rehellinen',
        'lapsi',
        'maa',
      ],
      correctAnswer: 'rehellinen',
    },

    {
      type: 'create-sentence',
      question: 'Estonia jest mała i piękna',
      choices: [
        'Pari',
        'ja',
        'on',
        'kaunis',
        'kiltti',
        'aina',
        'Viro',
        'pieni',
        'olen',
        'poika',
        'rehellinen',
      ],
      correctAnswer: 'Viro on pieni ja kaunis',
    },

    {
      type: 'single-choice',
      question: 'dziewczyna',
      choices: ['poika', 'aina', 'kuka', 'olen', 'tyttö', 'tuhma', 'olemee'],
      correctAnswer: 'tyttö',
    },

    {
      type: 'create-sentence',
      question: 'Jakiego rodzaju to jest pies?',
      choices: [
        'Tervetuloa',
        'olmee',
        'koira',
        'se',
        'tanssin',
        'poika',
        'aina',
        'on',
        'lapsi',
        'maa',
        'Millainen',
      ],
      correctAnswer: 'Millainen koira se on',
    },

    {
      type: 'create-sentence',
      question: 'Jesteś dobrym chłopakiem',
      choices: [
        'mukava',
        'aina',
        'kuka',
        'Olet',
        'tyttö',
        'tuhma',
        'olemee',
        'poika',
      ],
      correctAnswer: 'Olet mukava poika',
    },

    {
      type: 'single-choice',
      question: 'zajączek',
      choices: ['kaunis', 'kiltti', 'pupu', 'koira', 'aina', 'mies', 'lapsi'],
      correctAnswer: 'pupu',
    },

    {
      type: 'create-sentence',
      question: 'Ja mam zajączka',
      choices: [
        'Pari',
        'pupu',
        'olen',
        'ja',
        'on',
        'Millainen',
        'Minulla',
        'pieni',
      ],
      correctAnswer: 'Minulla on pupu',
    },

    {
      type: 'create-sentence',
      question: 'To jest małe i miłe',
      choices: [
        'Olet',
        'Se',
        'ja',
        'kaunis',
        'kiltti',
        'tanssin',
        'pieni',
        'on',
        'aina',
      ],
      correctAnswer: 'Se on pieni ja kiltti',
    },

    {
      type: 'create-sentence',
      question: 'Se on pieni ja kiltti',
      choices: [
        'miłe',
        'ty',
        'piękne',
        'szczere',
        'To',
        'Ten',
        'jest',
        'i',
        'małe',
        'znowu',
        'mam',
      ],
      correctAnswer: 'To jest małe i miłe',
    },

    {
      type: 'single-choice',
      question: 'niegrzeczny',
      choices: [
        'olmee',
        'tanssin',
        'poika',
        'aina',
        'rehellinen',
        'maa',
        'tuhma',
      ],
      correctAnswer: 'tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Ten kot jest niegrzeczny!',
      choices: [
        'Tämä',
        'kiltti',
        'tuhma',
        'ty',
        'ja',
        'Aina',
        'kissa',
        'aina',
        'Terve',
        'on',
      ],
      correctAnswer: 'Tämä kissa on tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Hänellä on sininen käärme',
      choices: [
        'kot',
        'Dziecko',
        'czerwonego',
        'zajączka',
        'węża',
        'ma',
        'nie ma',
        'niebieskiego',
        'Ona',
      ],
      correctAnswer: 'Ona ma niebieskiego węża',
    },

    {
      type: 'single-choice',
      question: 'sininen',
      choices: [
        'niebieski',
        'czerwony',
        'żółty',
        'zielony',
        'brązowy',
        'czarny',
      ],
      correctAnswer: 'niebieski',
    },
  ],
  questionsThree: [
    {
      type: 'create-sentence',
      question: 'Missä kaupunki on?',
      choices: [
        'Kto',
        'rozumie',
        'on',
        'Gdzie',
        'ja',
        'miasto',
        'jest',
        'go',
        'rower',
      ],
      correctAnswer: 'Gdzie jest miasto',
    },

    {
      type: 'single-choice',
      question: 'Gdzie',
      choices: ['tämä', 'minä', 'fin', 'missä', 'viro', 'millainen', 'nainen'],
      correctAnswer: 'missä',
    },

    {
      type: 'create-sentence',
      question: 'Piękna piosenka jest rosyjska',
      choices: [
        'laulu',
        'lapsi',
        'viro',
        'Ruotsi',
        'Kaunis',
        'to',
        'on',
        'venäläinen',
        'mies',
      ],
      correctAnswer: 'Kaunis laulu on venäläinen',
    },

    {
      type: 'create-sentence',
      question: 'Kaunis laulu on venäläinen',
      choices: [
        'kot',
        'jest',
        'szwecja',
        'tańcze',
        'Miła',
        'rosyjska',
        'piosenka',
        'Piękna',
        'też',
      ],
      correctAnswer: 'Piękna piosenka jest rosyjska',
    },

    {
      type: 'single-choice',
      question: 'venäläinen',
      choices: [
        'rosyjska',
        'Szwecja',
        'dziewczyna',
        'pierwszy',
        'wiem',
        'brązowy',
        'rzadko',
      ],
      correctAnswer: 'rosyjska',
    },

    {
      type: 'create-sentence',
      question: 'Oletteko te nyt pari?',
      choices: [
        'Powodzenia',
        'i',
        'Przepraszam',
        'zawsze',
        'teraz',
        'parą',
        'Jesteście',
        'Jesteśmy',
      ],
      correctAnswer: 'Jesteście teraz parą',
    },

    {
      type: 'single-choice',
      question: 'teraz',
      choices: [
        'pari',
        'talo',
        'yhdessä',
        'usein',
        'olen',
        'olemee',
        'lapsi',
        'nyt',
      ],
      correctAnswer: 'nyt',
    },

    {
      type: 'create-sentence',
      question: 'Ja tańcze',
      choices: [
        'Sinä',
        'ja',
        'ma',
        'aina',
        'tanssin',
        'maa',
        'Meillä',
        'Minä',
        'Pyry',
        'millainen',
      ],
      correctAnswer: 'Minä tanssin',
    },

    {
      type: 'single-choice',
      question: 'tanssin',
      choices: [
        'teraz',
        'używać',
        'tygrys',
        'jutro',
        'tańczyć',
        'telewizja',
        'zabawny',
      ],
      correctAnswer: 'tańczyć',
    },

    {
      type: 'create-sentence',
      question: 'Me olemme naimisissa',
      choices: [
        'Teraz',
        'kaunis',
        'małżeństwem',
        'lubie',
        'robie',
        'fikołka',
        'Jesteśmy',
        'Też',
      ],
      correctAnswer: 'Jesteśmy małżeństwem',
    },

    {
      type: 'create-sentence',
      question: 'He istuvat yhdessä',
      choices: [
        'On',
        'Ty',
        'siedzisz',
        'sam',
        'parą',
        'razem',
        'są',
        'Oni',
        'siedzą',
        'radio',
      ],
      correctAnswer: 'Oni siedzą razem',
    },

    {
      type: 'single-choice',
      question: 'istuvat',
      choices: [
        'tańczyć',
        'pies',
        'kot',
        'kobieta',
        'robić',
        'siedzą',
        'gotować',
      ],
      correctAnswer: 'siedzą',
    },

    {
      type: 'create-sentence',
      question: 'Oni siedzą razem',
      choices: [
        'Sinä',
        'Olet',
        'itket',
        'istuvat',
        'He',
        'rehellinen',
        'yhdessä',
        'usein',
      ],
      correctAnswer: 'He istuvat yhdessä',
    },

    {
      type: 'create-sentence',
      question: 'Missä te seisotte?',
      choices: [
        'Co',
        'Jak',
        'robisz',
        'tańczysz',
        'siedzisz',
        'Kim',
        'jesteś',
        'Gdzie',
        'stoisz',
      ],
      correctAnswer: 'Gdzie stoisz',
    },

    {
      type: 'create-sentence',
      question: 'Ty rzadko płaczesz i często się śmiejesz',
      choices: [
        'usein',
        'Ja',
        'itket',
        'Minulla',
        'pari',
        'aina',
        'Sinä',
        'fin',
        'ja',
        'to',
        'harvoin',
        'naurat',
      ],
      correctAnswer: 'Sinä itket harvoin ja naurat usein',
    },

    {
      type: 'create-sentence',
      question: 'Sinä itket harvoin ja naurat usein',
      choices: [
        'My',
        'często',
        'tańczymy',
        'i',
        'nie',
        'używamy',
        'Ty',
        'rzadko',
        'śmiejesz',
        'się',
        'płaczesz',
      ],
      correctAnswer: 'Ty rzadko płaczesz i często się śmiejesz',
    },

    {
      type: 'single-choice',
      question: 'płakać',
      choices: [
        'hauska',
        'tanssin',
        'paljon',
        'harvoin',
        'rehellinen',
        'millainen',
        'teillä',
      ],
      correctAnswer: 'harvoin',
    },

    {
      type: 'create-sentence',
      question: 'Minulla on uusi lelu',
      choices: [
        'Masz',
        'radio',
        'zajączka',
        'starą',
        'nową',
        'Mam',
        'zabawke',
        'Ona',
        'ma',
      ],
      correctAnswer: 'Mam nową zabawke',
    },

    {
      type: 'single-choice',
      question: 'uusi',
      choices: ['teraz', 'piękny', 'mały', 'kot', 'dom', 'starą', 'nowa'],
      correctAnswer: 'nowa',
    },

    {
      type: 'create-sentence',
      question: 'Sinulla on kaunis talo',
      choices: [
        'Mamy',
        'wiem',
        'telewizja',
        'Ty',
        'dwa',
        'dom',
        'piękny',
        'masz',
        'My',
        'kwiaty',
      ],
      correctAnswer: 'Ty masz piękny dom',
    },

    {
      type: 'single-choice',
      question: 'talo',
      choices: [
        'to',
        'razem',
        'używamy',
        'teraz',
        'pies',
        'tak',
        'dom',
        'dobra',
      ],
      correctAnswer: 'dom',
    },

    {
      type: 'create-sentence',
      question: 'Jaką masz saune?',
      choices: [
        'on',
        'tanssin',
        'sauna',
        'ja',
        'Pari',
        'Viro',
        'Millainen',
        'teillä',
        'todella',
      ],
      correctAnswer: 'Millainen sauna teillä on',
    },

    {
      type: 'create-sentence',
      question: 'Millainen sauna teillä on?',
      choices: [
        'tak',
        'Jutro',
        'jest',
        'Gdzie',
        'Jaką',
        'saune',
        'mamy',
        'mała',
        'masz',
        'Którą',
      ],
      correctAnswer: 'Jaką masz saune',
    },

    {
      type: 'create-sentence',
      question: 'My mamy dużą saune',
      choices: [
        'Meillä',
        'lapsi',
        'sinä',
        'sauna',
        'paljon',
        'pari',
        'on',
        'aina',
        'suuri',
        'laulu',
      ],
      correctAnswer: 'Meillä on suuri sauna',
    },

    {
      type: 'create-sentence',
      question: 'Meillä on suuri sauna',
      choices: [
        'Wy',
        'macie',
        'mamy',
        'saune',
        'waszą',
        'mamy',
        'piękną',
        'szczery',
        'dużą',
        'My',
      ],
      correctAnswer: 'My mamy dużą saune',
    },

    {
      type: 'create-sentence',
      question: 'Heillä on radio ja televisio',
      choices: [
        'i',
        'Oni',
        'lubie',
        'Ja',
        'Wy',
        'radio',
        'telewizje',
        'psa',
        'siedzą',
        'mają',
        'mam',
      ],
      correctAnswer: 'Oni mają radio i telewizje',
    },

    {
      type: 'create-sentence',
      question: 'Kaunis laulu on venäläinen',
      choices: [
        'kot',
        'jest',
        'szwecja',
        'tańcze',
        'Miła',
        'rosyjska',
        'piosenka',
        'Piękna',
        'też',
      ],
      correctAnswer: 'Piękna piosenka jest rosyjska',
    },

    {
      type: 'single-choice',
      question: 'venäläinen',
      choices: [
        'rosyjska',
        'Szwecja',
        'dziewczyna',
        'pierwszy',
        'wiem',
        'brązowy',
        'rzadko',
      ],
      correctAnswer: 'rosyjska',
    },

    {
      type: 'create-sentence',
      question: 'Ty rzadko płaczesz i często się śmiejesz',
      choices: [
        'usein',
        'Ja',
        'itket',
        'Minulla',
        'pari',
        'aina',
        'Sinä',
        'fin',
        'ja',
        'to',
        'harvoin',
        'naurat',
      ],
      correctAnswer: 'Sinä itket harvoin ja naurat usein',
    },

    {
      type: 'create-sentence',
      question: 'Missä kaupunki on?',
      choices: [
        'Kto',
        'rozumie',
        'on',
        'Gdzie',
        'ja',
        'miasto',
        'jest',
        'go',
        'rower',
      ],
      correctAnswer: 'Gdzie jest miasto',
    },

    {
      type: 'single-choice',
      question: 'Gdzie',
      choices: ['tämä', 'minä', 'fin', 'missä', 'viro', 'millainen', 'nainen'],
      correctAnswer: 'missä',
    },

    {
      type: 'create-sentence',
      question: 'Millainen sauna teillä on?',
      choices: [
        'tak',
        'Jutro',
        'jest',
        'Gdzie',
        'Jaką',
        'saune',
        'mamy',
        'mała',
        'masz',
        'Którą',
      ],
      correctAnswer: 'Jaką masz saune',
    },

    {
      type: 'single-choice',
      question: 'uusi',
      choices: ['teraz', 'piękny', 'mały', 'kot', 'dom', 'starą', 'nowa'],
      correctAnswer: 'nowa',
    },

    {
      type: 'single-choice',
      question: 'talo',
      choices: [
        'to',
        'razem',
        'używamy',
        'teraz',
        'pies',
        'tak',
        'dom',
        'dobra',
      ],
      correctAnswer: 'dom',
    },

    {
      type: 'create-sentence',
      question: 'Sinulla on kaunis talo',
      choices: [
        'Mamy',
        'wiem',
        'telewizja',
        'Ty',
        'dwa',
        'dom',
        'piękny',
        'masz',
        'My',
        'kwiaty',
      ],
      correctAnswer: 'Ty masz piękny dom',
    },

    {
      type: 'create-sentence',
      question: 'Sinä itket harvoin ja naurat usein',
      choices: [
        'My',
        'często',
        'tańczymy',
        'i',
        'nie',
        'używamy',
        'Ty',
        'rzadko',
        'śmiejesz',
        'się',
        'płaczesz',
      ],
      correctAnswer: 'Ty rzadko płaczesz i często się śmiejesz',
    },

    {
      type: 'single-choice',
      question: 'płakać',
      choices: [
        'hauska',
        'tanssin',
        'paljon',
        'harvoin',
        'rehellinen',
        'millainen',
        'teillä',
      ],
      correctAnswer: 'harvoin',
    },

    {
      type: 'create-sentence',
      question: 'Missä kaupunki on?',
      choices: [
        'Kto',
        'rozumie',
        'on',
        'Gdzie',
        'ja',
        'miasto',
        'jest',
        'go',
        'rower',
      ],
      correctAnswer: 'Gdzie jest miasto',
    },

    {
      type: 'single-choice',
      question: 'Gdzie',
      choices: ['tämä', 'minä', 'fin', 'missä', 'viro', 'millainen', 'nainen'],
      correctAnswer: 'missä',
    },

    {
      type: 'create-sentence',
      question: 'Piękna piosenka jest rosyjska',
      choices: [
        'laulu',
        'lapsi',
        'viro',
        'Ruotsi',
        'Kaunis',
        'to',
        'on',
        'venäläinen',
        'mies',
      ],
      correctAnswer: 'Kaunis laulu on venäläinen',
    },

    {
      type: 'create-sentence',
      question: 'Kaunis laulu on venäläinen',
      choices: [
        'kot',
        'jest',
        'szwecja',
        'tańcze',
        'Miła',
        'rosyjska',
        'piosenka',
        'Piękna',
        'też',
      ],
      correctAnswer: 'Piękna piosenka jest rosyjska',
    },

    {
      type: 'single-choice',
      question: 'venäläinen',
      choices: [
        'rosyjska',
        'Szwecja',
        'dziewczyna',
        'pierwszy',
        'wiem',
        'brązowy',
        'rzadko',
      ],
      correctAnswer: 'rosyjska',
    },

    {
      type: 'create-sentence',
      question: 'Oletteko te nyt pari?',
      choices: [
        'Powodzenia',
        'i',
        'Przepraszam',
        'zawsze',
        'teraz',
        'parą',
        'Jesteście',
        'Jesteśmy',
      ],
      correctAnswer: 'Jesteście teraz parą',
    },

    {
      type: 'single-choice',
      question: 'teraz',
      choices: [
        'pari',
        'talo',
        'yhdessä',
        'usein',
        'istuvat',
        'olen',
        'olemee',
        'lapsi',
        'nyt',
      ],
      correctAnswer: 'nyt',
    },

    {
      type: 'create-sentence',
      question: 'Ja tańcze',
      choices: [
        'Sinä',
        'ja',
        'ma',
        'aina',
        'tanssin',
        'maa',
        'Meillä',
        'Minä',
        'Pyry',
        'millainen',
      ],
      correctAnswer: 'Minä tanssin',
    },

    {
      type: 'single-choice',
      question: 'tanssin',
      choices: [
        'teraz',
        'używać',
        'tygrys',
        'jutro',
        'tańczyć',
        'telewizja',
        'zabawny',
      ],
      correctAnswer: 'tańczyć',
    },

    {
      type: 'create-sentence',
      question: 'Me olemme naimisissa',
      choices: [
        'Teraz',
        'kaunis',
        'małżeństwem',
        'lubie',
        'robie',
        'fikołka',
        'Jesteśmy',
        'Też',
      ],
      correctAnswer: 'Jesteśmy małżeństwem',
    },

    {
      type: 'create-sentence',
      question: 'He istuvat yhdessä',
      choices: [
        'On',
        'Ty',
        'siedzisz',
        'sam',
        'parą',
        'razem',
        'są',
        'Oni',
        'siedzą',
        'radio',
      ],
      correctAnswer: 'Oni siedzą razem',
    },

    {
      type: 'single-choice',
      question: 'istuvat',
      choices: [
        'tańczyć',
        'pies',
        'kot',
        'kobieta',
        'robić',
        'siedzą',
        'gotować',
      ],
      correctAnswer: 'siedzą',
    },

    {
      type: 'create-sentence',
      question: 'Oni siedzą razem',
      choices: [
        'Sinä',
        'Olet',
        'itket',
        'istuvat',
        'He',
        'rehellinen',
        'yhdessä',
        'usein',
      ],
      correctAnswer: 'He istuvat yhdessä',
    },

    {
      type: 'create-sentence',
      question: 'Missä te seisotte?',
      choices: [
        'Co',
        'Jak',
        'robisz',
        'tańczysz',
        'siedzisz',
        'Kim',
        'jesteś',
        'Gdzie',
        'stoisz',
      ],
      correctAnswer: 'Gdzie stoisz',
    },

    {
      type: 'create-sentence',
      question: 'Ty rzadko płaczesz i często się śmiejesz',
      choices: [
        'usein',
        'Ja',
        'itket',
        'Minulla',
        'pari',
        'aina',
        'Sinä',
        'fin',
        'ja',
        'to',
        'harvoin',
        'naurat',
      ],
      correctAnswer: 'Sinä itket harvoin ja naurat usein',
    },

    {
      type: 'create-sentence',
      question: 'Sinä itket harvoin ja naurat usein',
      choices: [
        'My',
        'często',
        'tańczymy',
        'i',
        'nie',
        'używamy',
        'Ty',
        'rzadko',
        'śmiejesz',
        'się',
        'płaczesz',
      ],
      correctAnswer: 'Ty rzadko płaczesz i często się śmiejesz',
    },

    {
      type: 'single-choice',
      question: 'płakać',
      choices: [
        'hauska',
        'tanssin',
        'paljon',
        'harvoin',
        'rehellinen',
        'millainen',
        'teillä',
      ],
      correctAnswer: 'harvoin',
    },

    {
      type: 'create-sentence',
      question: 'Minulla on uusi lelu',
      choices: [
        'Masz',
        'radio',
        'zajączka',
        'starą',
        'nową',
        'Mam',
        'zabawke',
        'Ona',
        'ma',
      ],
      correctAnswer: 'Mam nową zabawke',
    },

    {
      type: 'single-choice',
      question: 'uusi',
      choices: ['teraz', 'piękny', 'mały', 'kot', 'dom', 'starą', 'nowa'],
      correctAnswer: 'nowa',
    },

    {
      type: 'create-sentence',
      question: 'Sinulla on kaunis talo',
      choices: [
        'Mamy',
        'wiem',
        'telewizja',
        'Ty',
        'dwa',
        'dom',
        'piękny',
        'masz',
        'My',
        'kwiaty',
      ],
      correctAnswer: 'Ty masz piękny dom',
    },

    {
      type: 'single-choice',
      question: 'talo',
      choices: [
        'to',
        'razem',
        'używamy',
        'teraz',
        'pies',
        'tak',
        'dom',
        'dobra',
      ],
      correctAnswer: 'dom',
    },

    {
      type: 'create-sentence',
      question: 'Jaką masz saune?',
      choices: [
        'on',
        'tanssin',
        'sauna',
        'ja',
        'Pari',
        'Viro',
        'Millainen',
        'teillä',
        'todella',
      ],
      correctAnswer: 'Millainen sauna teillä on',
    },

    {
      type: 'create-sentence',
      question: 'Millainen sauna teillä on?',
      choices: [
        'tak',
        'Jutro',
        'jest',
        'Gdzie',
        'Jaką',
        'saune',
        'mamy',
        'mała',
        'masz',
        'Którą',
      ],
      correctAnswer: 'Jaką masz saune',
    },

    {
      type: 'create-sentence',
      question: 'My mamy dużą saune',
      choices: [
        'Meillä',
        'lapsi',
        'sinä',
        'sauna',
        'paljon',
        'pari',
        'on',
        'aina',
        'suuri',
        'laulu',
      ],
      correctAnswer: 'Meillä on suuri sauna',
    },

    {
      type: 'create-sentence',
      question: 'Meillä on suuri sauna',
      choices: [
        'Wy',
        'macie',
        'mamy',
        'saune',
        'waszą',
        'mamy',
        'piękną',
        'szczery',
        'dużą',
        'My',
      ],
      correctAnswer: 'My mamy dużą saune',
    },

    {
      type: 'create-sentence',
      question: 'Heillä on radio ja televisio',
      choices: [
        'i',
        'Oni',
        'lubie',
        'Ja',
        'Wy',
        'radio',
        'telewizje',
        'psa',
        'siedzą',
        'mają',
        'mam',
      ],
      correctAnswer: 'Oni mają radio i telewizje',
    },

    {
      type: 'create-sentence',
      question: 'Kaunis laulu on venäläinen',
      choices: [
        'kot',
        'jest',
        'szwecja',
        'tańcze',
        'Miła',
        'rosyjska',
        'piosenka',
        'Piękna',
        'też',
      ],
      correctAnswer: 'Piękna piosenka jest rosyjska',
    },

    {
      type: 'single-choice',
      question: 'venäläinen',
      choices: [
        'rosyjska',
        'Szwecja',
        'dziewczyna',
        'pierwszy',
        'wiem',
        'brązowy',
        'rzadko',
      ],
      correctAnswer: 'rosyjska',
    },

    {
      type: 'create-sentence',
      question: 'Ty rzadko płaczesz i często się śmiejesz',
      choices: [
        'usein',
        'Ja',
        'itket',
        'Minulla',
        'pari',
        'aina',
        'Sinä',
        'fin',
        'ja',
        'to',
        'harvoin',
        'naurat',
      ],
      correctAnswer: 'Sinä itket harvoin ja naurat usein',
    },

    {
      type: 'create-sentence',
      question: 'Missä kaupunki on?',
      choices: [
        'Kto',
        'rozumie',
        'on',
        'Gdzie',
        'ja',
        'miasto',
        'jest',
        'go',
        'rower',
      ],
      correctAnswer: 'Gdzie jest miasto',
    },

    {
      type: 'single-choice',
      question: 'Gdzie',
      choices: ['tämä', 'minä', 'fin', 'missä', 'viro', 'millainen', 'nainen'],
      correctAnswer: 'missä',
    },

    {
      type: 'create-sentence',
      question: 'Millainen sauna teillä on?',
      choices: [
        'tak',
        'Jutro',
        'jest',
        'Gdzie',
        'Jaką',
        'saune',
        'mamy',
        'mała',
        'masz',
        'Którą',
      ],
      correctAnswer: 'Jaką masz saune',
    },

    {
      type: 'single-choice',
      question: 'uusi',
      choices: ['teraz', 'piękny', 'mały', 'nowy', 'dom', 'starą', 'nowa'],
      correctAnswer: 'nowa',
    },

    {
      type: 'single-choice',
      question: 'talo',
      choices: [
        'to',
        'razem',
        'używamy',
        'teraz',
        'pies',
        'tak',
        'dom',
        'dobra',
      ],
      correctAnswer: 'dom',
    },

    {
      type: 'create-sentence',
      question: 'Sinulla on kaunis talo',
      choices: [
        'Mamy',
        'wiem',
        'telewizja',
        'Ty',
        'dwa',
        'dom',
        'piękny',
        'masz',
        'My',
        'kwiaty',
      ],
      correctAnswer: 'Ty masz piękny dom',
    },

    {
      type: 'create-sentence',
      question: 'Sinä itket harvoin ja naurat usein',
      choices: [
        'My',
        'często',
        'tańczymy',
        'i',
        'nie',
        'używamy',
        'Ty',
        'rzadko',
        'śmiejesz',
        'się',
        'płaczesz',
      ],
      correctAnswer: 'Ty rzadko płaczesz i często się śmiejesz',
    },

    {
      type: 'single-choice',
      question: 'płakać',
      choices: [
        'hauska',
        'tanssin',
        'paljon',
        'harvoin',
        'rehellinen',
        'millainen',
        'teillä',
      ],
      correctAnswer: 'harvoin',
    },

    {
      type: 'create-sentence',
      question: 'Missä kaupunki on?',
      choices: [
        'Kto',
        'rozumie',
        'on',
        'Gdzie',
        'ja',
        'miasto',
        'jest',
        'go',
        'rower',
      ],
      correctAnswer: 'Gdzie jest miasto',
    },

    {
      type: 'single-choice',
      question: 'Gdzie',
      choices: ['tämä', 'minä', 'fin', 'missä', 'viro', 'millainen', 'nainen'],
      correctAnswer: 'missä',
    },

    {
      type: 'create-sentence',
      question: 'Piękna piosenka jest rosyjska',
      choices: [
        'laulu',
        'lapsi',
        'viro',
        'Ruotsi',
        'Kaunis',
        'to',
        'on',
        'venäläinen',
        'mies',
      ],
      correctAnswer: 'Kaunis laulu on venäläinen',
    },

    {
      type: 'create-sentence',
      question: 'Kaunis laulu on venäläinen',
      choices: [
        'kot',
        'jest',
        'szwecja',
        'tańcze',
        'Miła',
        'rosyjska',
        'piosenka',
        'Piękna',
        'też',
      ],
      correctAnswer: 'Piękna piosenka jest rosyjska',
    },

    {
      type: 'single-choice',
      question: 'venäläinen',
      choices: [
        'rosyjska',
        'Szwecja',
        'dziewczyna',
        'pierwszy',
        'wiem',
        'brązowy',
        'rzadko',
      ],
      correctAnswer: 'rosyjska',
    },

    {
      type: 'create-sentence',
      question: 'Oletteko te nyt pari?',
      choices: [
        'Powodzenia',
        'i',
        'Przepraszam',
        'zawsze',
        'teraz',
        'parą',
        'Jesteście',
        'Jesteśmy',
      ],
      correctAnswer: 'Jesteście teraz parą',
    },

    {
      type: 'single-choice',
      question: 'teraz',
      choices: [
        'pari',
        'talo',
        'yhdessä',
        'usein',
        'istuvat',
        'olen',
        'olemee',
        'lapsi',
        'nyt',
      ],
      correctAnswer: 'nyt',
    },

    {
      type: 'create-sentence',
      question: 'Ja tańcze',
      choices: [
        'Sinä',
        'ja',
        'ma',
        'aina',
        'tanssin',
        'maa',
        'Meillä',
        'Minä',
        'Pyry',
        'millainen',
      ],
      correctAnswer: 'Minä tanssin',
    },

    {
      type: 'single-choice',
      question: 'tanssin',
      choices: [
        'teraz',
        'używać',
        'tygrys',
        'jutro',
        'tańczyć',
        'telewizja',
        'zabawny',
      ],
      correctAnswer: 'tańczyć',
    },

    {
      type: 'create-sentence',
      question: 'Me olemme naimisissa',
      choices: [
        'Teraz',
        'kaunis',
        'małżeństwem',
        'lubie',
        'robie',
        'fikołka',
        'Jesteśmy',
        'Też',
      ],
      correctAnswer: 'Jesteśmy małżeństwem',
    },

    {
      type: 'create-sentence',
      question: 'He istuvat yhdessä',
      choices: [
        'On',
        'Ty',
        'siedzisz',
        'sam',
        'parą',
        'razem',
        'są',
        'Oni',
        'siedzą',
        'radio',
      ],
      correctAnswer: 'Oni siedzą razem',
    },

    {
      type: 'single-choice',
      question: 'istuvat',
      choices: [
        'tańczyć',
        'pies',
        'kot',
        'kobieta',
        'robić',
        'siedzą',
        'gotować',
      ],
      correctAnswer: 'siedzą',
    },

    {
      type: 'create-sentence',
      question: 'Oni siedzą razem',
      choices: [
        'Sinä',
        'Olet',
        'itket',
        'istuvat',
        'He',
        'rehellinen',
        'yhdessä',
        'usein',
      ],
      correctAnswer: 'He istuvat yhdessä',
    },

    {
      type: 'create-sentence',
      question: 'Missä te seisotte?',
      choices: [
        'Co',
        'Jak',
        'robisz',
        'tańczysz',
        'siedzisz',
        'Kim',
        'jesteś',
        'Gdzie',
        'stoisz',
      ],
      correctAnswer: 'Gdzie stoisz',
    },

    {
      type: 'create-sentence',
      question: 'Ty rzadko płaczesz i często się śmiejesz',
      choices: [
        'usein',
        'Ja',
        'itket',
        'Minulla',
        'pari',
        'aina',
        'Sinä',
        'fin',
        'ja',
        'to',
        'harvoin',
        'naurat',
      ],
      correctAnswer: 'Sinä itket harvoin ja naurat usein',
    },

    {
      type: 'create-sentence',
      question: 'Sinä itket harvoin ja naurat usein',
      choices: [
        'My',
        'często',
        'tańczymy',
        'i',
        'nie',
        'używamy',
        'Ty',
        'rzadko',
        'śmiejesz',
        'się',
        'płaczesz',
      ],
      correctAnswer: 'Ty rzadko płaczesz i często się śmiejesz',
    },

    {
      type: 'single-choice',
      question: 'płakać',
      choices: [
        'hauska',
        'tanssin',
        'paljon',
        'harvoin',
        'rehellinen',
        'millainen',
        'teillä',
      ],
      correctAnswer: 'harvoin',
    },

    {
      type: 'create-sentence',
      question: 'Minulla on uusi lelu',
      choices: [
        'Masz',
        'radio',
        'zajączka',
        'starą',
        'nową',
        'Mam',
        'zabawke',
        'Ona',
        'ma',
      ],
      correctAnswer: 'Mam nową zabawke',
    },

    {
      type: 'single-choice',
      question: 'uusi',
      choices: ['teraz', 'piękny', 'mały', 'kot', 'dom', 'starą', 'nowa'],
      correctAnswer: 'nowa',
    },

    {
      type: 'create-sentence',
      question: 'Sinulla on kaunis talo',
      choices: [
        'Mamy',
        'wiem',
        'telewizja',
        'Ty',
        'dwa',
        'dom',
        'piękny',
        'masz',
        'My',
        'kwiaty',
      ],
      correctAnswer: 'Ty masz piękny dom',
    },

    {
      type: 'single-choice',
      question: 'talo',
      choices: [
        'to',
        'razem',
        'używamy',
        'teraz',
        'pies',
        'tak',
        'dom',
        'dobra',
      ],
      correctAnswer: 'dom',
    },

    {
      type: 'create-sentence',
      question: 'Jaką masz saune?',
      choices: [
        'on',
        'tanssin',
        'sauna',
        'ja',
        'Pari',
        'Viro',
        'Millainen',
        'teillä',
        'todella',
      ],
      correctAnswer: 'Millainen sauna teillä on',
    },

    {
      type: 'create-sentence',
      question: 'Millainen sauna teillä on?',
      choices: [
        'tak',
        'Jutro',
        'jest',
        'Gdzie',
        'Jaką',
        'saune',
        'mamy',
        'mała',
        'masz',
        'Którą',
      ],
      correctAnswer: 'Jaką masz saune',
    },

    {
      type: 'create-sentence',
      question: 'My mamy dużą saune',
      choices: [
        'Meillä',
        'lapsi',
        'sinä',
        'sauna',
        'paljon',
        'pari',
        'on',
        'aina',
        'suuri',
        'laulu',
      ],
      correctAnswer: 'Meillä on suuri sauna',
    },

    {
      type: 'create-sentence',
      question: 'Meillä on suuri sauna',
      choices: [
        'Wy',
        'macie',
        'mamy',
        'saune',
        'waszą',
        'mamy',
        'piękną',
        'szczery',
        'dużą',
        'My',
      ],
      correctAnswer: 'My mamy dużą saune',
    },

    {
      type: 'create-sentence',
      question: 'Heillä on radio ja televisio',
      choices: [
        'i',
        'Oni',
        'lubie',
        'Ja',
        'Wy',
        'radio',
        'telewizje',
        'psa',
        'siedzą',
        'mają',
        'mam',
      ],
      correctAnswer: 'Oni mają radio i telewizje',
    },

    {
      type: 'create-sentence',
      question: 'Kaunis laulu on venäläinen',
      choices: [
        'kot',
        'jest',
        'szwecja',
        'tańcze',
        'Miła',
        'rosyjska',
        'piosenka',
        'Piękna',
        'też',
      ],
      correctAnswer: 'Piękna piosenka jest rosyjska',
    },

    {
      type: 'single-choice',
      question: 'venäläinen',
      choices: [
        'rosyjska',
        'Szwecja',
        'dziewczyna',
        'pierwszy',
        'wiem',
        'brązowy',
        'rzadko',
      ],
      correctAnswer: 'rosyjska',
    },

    {
      type: 'create-sentence',
      question: 'Ty rzadko płaczesz i często się śmiejesz',
      choices: [
        'usein',
        'Ja',
        'itket',
        'Minulla',
        'pari',
        'aina',
        'Sinä',
        'fin',
        'ja',
        'to',
        'harvoin',
        'naurat',
      ],
      correctAnswer: 'Sinä itket harvoin ja naurat usein',
    },

    {
      type: 'create-sentence',
      question: 'Missä kaupunki on?',
      choices: [
        'Kto',
        'rozumie',
        'on',
        'Gdzie',
        'ja',
        'miasto',
        'jest',
        'go',
        'rower',
      ],
      correctAnswer: 'Gdzie jest miasto',
    },

    {
      type: 'single-choice',
      question: 'Gdzie',
      choices: ['tämä', 'minä', 'fin', 'missä', 'viro', 'millainen', 'nainen'],
      correctAnswer: 'missä',
    },

    {
      type: 'create-sentence',
      question: 'Millainen sauna teillä on?',
      choices: [
        'tak',
        'Jutro',
        'jest',
        'Gdzie',
        'Jaką',
        'saune',
        'mamy',
        'mała',
        'masz',
        'Którą',
      ],
      correctAnswer: 'Jaką masz saune',
    },

    {
      type: 'single-choice',
      question: 'uusi',
      choices: ['teraz', 'piękny', 'mały', 'kot', 'dom', 'starą', 'nowa'],
      correctAnswer: 'nowa',
    },

    {
      type: 'single-choice',
      question: 'talo',
      choices: [
        'to',
        'razem',
        'używamy',
        'teraz',
        'pies',
        'tak',
        'dom',
        'dobra',
      ],
      correctAnswer: 'dom',
    },

    {
      type: 'create-sentence',
      question: 'Sinulla on kaunis talo',
      choices: [
        'Mamy',
        'wiem',
        'telewizja',
        'Ty',
        'dwa',
        'dom',
        'piękny',
        'masz',
        'My',
        'kwiaty',
      ],
      correctAnswer: 'Ty masz piękny dom',
    },

    {
      type: 'create-sentence',
      question: 'Sinä itket harvoin ja naurat usein',
      choices: [
        'My',
        'często',
        'tańczymy',
        'i',
        'nie',
        'używamy',
        'Ty',
        'rzadko',
        'śmiejesz',
        'się',
        'płaczesz',
      ],
      correctAnswer: 'Ty rzadko płaczesz i często się śmiejesz',
    },

    {
      type: 'single-choice',
      question: 'płakać',
      choices: [
        'hauska',
        'tanssin',
        'paljon',
        'harvoin',
        'rehellinen',
        'millainen',
        'teillä',
      ],
      correctAnswer: 'harvoin',
    },
  ],
}

export const banners = {
  QuizOne: {
    top: [],

    right: [],

    left: [],

    pupup: [],
  },

  QuizTwo: {
    top: [
      'media/TwoTop/70K-Huincha-mobile-1920x80-n.webp',
      'media/TwoTop/AABC-Footer-Banner-CTA.jpg',
      'media/TwoTop/banner001.png',
      'media/TwoTop/div5trl.jpg',
      'media/TwoTop/flirdesk.gif',
      'media/TwoTop/free-delivery.webp',
      'media/TwoTop/widestjigglin.webp',
      'media/TwoTop/ModuleImage.HP_Header_Xbox.e44e221333844f178437a1acaaf39a36.jpg',
      'media/TwoTop/1920x80_32.jpg',
      'media/TwoTop/O1CN014nMCUb2JJiDfhBrua_!!2053469401.png',
      'media/TwoTop/1710467598811.webp',
    ],

    right: [
      'media/TwoRight/200x750.jpg',
      'media/TwoRight/96762d770fcf6e3c7c309674f308e5a5.jpg',
      'media/TwoRight/20191123_01_03.jpg',
      'media/TwoRight/511238961bf2e32e871ba5897c16dcf5.jpg',
      'media/TwoRight/bdch-pictures.webp',
      'media/TwoRight/chapman-poster.jpg',
      'media/TwoRight/cream-tea.jpg',
      'media/TwoRight/crunch-cat.gif',
      'media/TwoRight/Edible-Monterey-Bay-Ad-320-x-1200-px.webp',
      'media/TwoRight/junglescout-discount.jpg',
      'media/TwoRight/matita-staedtler-lumograph-10h-scatola-12pz.jpg',
      'media/TwoRight/moore-standing-forte-dei-marmi.jpg',
      'media/TwoRight/Staff-of-Life-Newsletter-Sponsorship-Spring-2024.webp',
      'media/TwoRight/VC_Culinary_Week_2024_Edible_320x1200_Final.webp',
    ],

    left: [
      'media/TwoLeft/6c0391a6157284e2ea3f54bf210ded1c.jpg',
      'media/TwoLeft/22.webp',
      'media/TwoLeft/36e7064a4a650f60f25586e0f01ac0e4.jpg',
      'media/TwoLeft/64b025be-37fe-8de3-9c39-a8ce10c91e0d.webp',
      'media/TwoLeft/annanadia1.webp',
      'media/TwoLeft/b2b2ba29074f0f3a4ae2e799f89aef64_w200.gif',
      'media/TwoLeft/banerpng.png',
      'media/TwoLeft/banner1_1024x1024.jpeg',
      'media/TwoLeft/eDigest-vertical-banner-with-team.jpg',
      'media/TwoLeft/emma-odonnell-2019.png',
      'media/TwoLeft/f42232ea372f1435060088c1acee9a2b_w200.gif',
      'media/TwoLeft/jam-side-200x750.jpg',
      'media/TwoLeft/studybanner.jpg',
      'media/TwoLeft/test1.webp',
      'media/TwoLeft/widetime.gif',
    ],

    popup: [],
  },
  QuizThree: {
    top: [
      'media/ThreeTop/123.gif',
      'media/ThreeTop/1920x120.gif',
      'media/ThreeTop/0884304.gif',
      'media/ThreeTop/345.gif',
      'media/ThreeTop/home-full-1-top-brands-pc.gif',
      'media/ThreeTop/Isetta.gif',
      'media/ThreeTop/KBC-SW-Digital-Ad-V2-1920x120.gif',
      'media/ThreeTop/Nowruz.gif',
      'media/ThreeTop/pobrane.gif',
      'media/ThreeTop/PUIG-BANNER-GIF2.gif',
      'media/ThreeTop/separador_pocodadraga1-26775281.gif',
    ],

    right: [
      'media/ThreeRight/1edf827c817571f2c374e88458227a49_w200.gif',
      'media/ThreeRight/3d6ab785ac3a04fa805dfb1b17f4a09e_w200.gif',
      'media/ThreeRight/4d37344593ae715cb7ad288a1585d3df_w200.gif',
      'media/ThreeRight/84f83263c1b5ba8866b782392322f32f_w200.gif',
      'media/ThreeRight/90a10b39c6c347509c6fd7adcec20510.webp',
      'media/ThreeRight/245bb5dd6875abeeebc3ad3c01079068_w200.gif',
      'media/ThreeRight/665c47bee147c973885289b2c213a52a_w200.gif',
      'media/ThreeRight/906cb3daf596e4a08bcc6dee8ef43008_w200.gif',
      'media/ThreeRight/16699f2438f918d522daf7f815ff3af6_w200.gif',
      'media/ThreeRight/b6cf699ee4b3b9d0b87ae2fa6fc5b288_w200.gif',
      'media/ThreeRight/b9a39b9a661c6a826f7cdfba195543de_w200.gif',
      'media/ThreeRight/b43be1f405442df37ceadcea769cd260_w200.gif',
      'media/ThreeRight/BDD_TERMINATOR_200x750.gif',
    ],

    left: [
      'media/ThreeLeft/f92639155b29a1a38e30d322ab2d6e2b_w200.gif',
      'media/ThreeLeft/fl3n7_.gif',
      'media/ThreeLeft/giphy (1).gif',
      'media/ThreeLeft/IMG_0113.gif',
      'media/ThreeLeft/luftballons.gif',
      'media/ThreeLeft/SC10_ReddishLayup_IB_v2.gif',
      'media/ThreeLeft/TelescopingColumn.webp',
      'media/ThreeLeft/tutHarmlessTrap.gif',
      'media/ThreeLeft/unnamed.gif',
      'media/ThreeLeft/อัพเดทเกมใหม่.gif',
    ],

    popup: [
      'media/Popup/biedronka.gif',
      'media/Popup/galaxy_z_flip.gif',
      'media/Popup/kaufland_grill.gif',
      'media/Popup/kebab_rollo_zabka.gif',
      'media/Popup/lidl_najtanszy.gif',
      'media/Popup/lidl_zakupy.gif',
      'media/Popup/media_markt_raty.gif',
      'media/Popup/orange.gif',
      'media/Popup/provident_pozyczka.gif',
      'media/Popup/t_mobile.gif',
    ],
  },
}

export const resultInitialState = {
  score: 0,
  correctAnswers: 0,
  wrongAnswers: 0,
}
