export const quizQuestions = {
  questionsOne: [
    {
      type: 'single-choice',
      question: 'Cześć!',
      choices: ['Elsa', 'Terve', 'Tervetuloa', 'Onnea'],
      correctAnswer: 'Terve',
    },

    {
      type: 'create-sentence',
      question: 'Cześć! Kim jesteś? ',
      choices: [
        'Kuka',
        'mies',
        'sauna',
        'olet',
        'sinä',
        'Terve',
        'Onnea',
        'hän',
      ],
      correctAnswer: 'Terve kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Otso',
      choices: ['Terve', 'Onnea', 'Otso', 'olemee', 'Minä', 'olen'],
      correctAnswer: 'Minä olen Otso',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim jesteś?',
      choices: [
        'Anteeksi',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'tanssin',
        'Pari',
        'nyt',
        'todella',
      ],
      correctAnswer: 'Anteeksi kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Elsa',
      choices: [
        'Elsa',
        'Terve',
        'Tervetuloa',
        'Onnea',
        'Minä',
        'olemee',
        'olen',
      ],
      correctAnswer: 'Minä olen Elsa',
    },

    {
      type: 'single-choice',
      question: 'Witam!',
      choices: ['Terve', 'Tervetuloa', 'Onnea', 'Otso', 'olemee'],
      correctAnswer: 'Tervetuloa',
    },

    {
      type: 'create-sentence',
      question: 'Jej! Powodzenia!',
      choices: ['Anteeksi', 'Onnea', 'Sinä', 'olet', 'tanssin', 'Pari', 'Jee'],
      correctAnswer: 'Jee Onnea',
    },

    {
      type: 'create-sentence',
      question: 'Pyry, jesteś zabawny',
      choices: [
        'Onnea',
        'Pyry',
        'sinä',
        'olen',
        'olet',
        'lapsi',
        'hauska',
        'aina',
        'paljon',
      ],
      correctAnswer: 'Pyry sinä olet hauska',
    },

    {
      type: 'create-sentence',
      question: 'Kippis ja paljon onnea!',
      choices: [
        'Cześć',
        ' Jestem',
        ' Zdrowie',
        ' ja',
        ' ona',
        ' pije',
        ' Witam',
        ' powodzenia',
        ' i',
      ],
      correctAnswer: 'Zdrowie i powodzenia',
    },

    {
      type: 'create-sentence',
      question: 'Zdrowie i powodzenia!',
      choices: [
        'ja',
        'Kippis',
        ' lapsi',
        ' väinö',
        ' mies',
        ' hauska',
        ' onnea',
        ' sinä',
        ' olen',
        ' paljon',
      ],
      correctAnswer: 'Kippis ja paljon onnea',
    },

    {
      type: 'single-choice',
      question: 'Nainen',
      choices: ['nie', ' mężczyzna', ' kobieta', ' dziecko', 'nie wiem'],
      correctAnswer: 'kobieta',
    },

    {
      type: 'create-sentence',
      question: 'Elsa on nainen',
      choices: [
        'Otso',
        ' ma',
        ' Elsa',
        ' dzieckiem',
        ' kobietą',
        ' nie',
        ' jest',
      ],
      correctAnswer: 'Elsa jest kobietą',
    },

    {
      type: 'create-sentence',
      question: 'Kuba on mies',
      choices: [
        'miesiąc',
        ' Kuba',
        ' ma',
        ' mężczyzną ',
        'miejsce',
        ' robi',
        ' jest',
      ],
      correctAnswer: 'Kuba jest mężczyzną',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Otso',
      choices: [
        'Pyry',
        'Otso',
        'olemee',
        'olen',
        ' kuka',
        'Terve',
        'sinä',
        'olet',
        'Minä',
        '',
      ],
      correctAnswer: 'Minä olen Pyry',
    },

    {
      type: 'single-choice',
      question: 'Anteeksi',
      choices: ['Dziękuje', ' Przepraszam', ' Narazie', ' Cześć', ' Usiądź'],
      correctAnswer: 'Przepraszam',
    },

    {
      type: 'single-choice',
      question: 'Dziecko',
      choices: ['lapsi', ' väinö', ' mies', ' hauska', ' onnea', ' sinä '],
      correctAnswer: 'lapsi',
    },

    {
      type: 'create-sentence',
      question: 'Kuka hän on?',
      choices: ['Kim', ' Co', ' to', ' jest', ' Gdzie', ' ona', ' Jakie'],
      correctAnswer: 'Kim ona jest',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim ona jest?',
      choices: ['lapsi', ' kuka', ' on', ' Anteeksi', ' mies', ' hän', ' sinä'],
      correctAnswer: 'Anteeksi, kuka hän on',
    },

    {
      type: 'single-choice',
      question: 'Mężczyzna',
      choices: ['nainen', ' paljon', ' tanssin', ' väinö', ' mies'],
      correctAnswer: 'mies ',
    },

    {
      type: 'single-choice',
      question: 'przystojny',
      choices: ['kaunis', ' komea', ' kota', ' hauska', ' onnea', ' todella'],
      correctAnswer: 'komea',
    },

    {
      type: 'single-choice',
      question: 'Finlandia',
      choices: ['Fin', ' Pari', ' Suomi', ' Aina', ' Tervetuloa'],
      correctAnswer: 'Suomi',
    },

    {
      type: 'single-choice',
      question: 'Aina',
      choices: ['zabawny', ' pierwszy', ' znowu', ' zawsze', ' wiem '],
      correctAnswer: 'zawsze',
    },

    {
      type: 'create-sentence',
      question: 'Finlandia jest zawsze piękna',
      choices: [
        'nainen',
        ' aina',
        ' Anteeksi',
        ' on',
        ' kaunis',
        'Suomi',
        ' todella',
        ' sinä',
      ],
      correctAnswer: 'Suomi on aina kaunis',
    },

    {
      type: 'create-sentence',
      question: 'Sinä olet todella komea',
      choices: [
        'naprawde',
        ' Witam',
        ' Dziękuje',
        ' przystojny',
        ' piękna',
        ' Jesteś',
        ' pije ',
      ],
      correctAnswer: 'Jesteś naprawde przystojny',
    },

    {
      type: 'single-choice',
      question: 'Cześć!',
      choices: ['Elsa', 'Terve', 'Tervetuloa', 'Onnea'],
      correctAnswer: 'Terve',
    },

    {
      type: 'single-choice',
      question: 'Dziecko',
      choices: ['lapsi', ' väinö', ' mies', ' hauska', ' onnea', ' sinä '],
      correctAnswer: 'lapsi',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Elsa',
      choices: [
        'Elsa',
        'Terve',
        'Tervetuloa',
        'Onnea',
        'Minä',
        'olemee',
        'olen',
      ],
      correctAnswer: 'Minä olen Elsa',
    },

    {
      type: 'create-sentence',
      question: 'Cześć! Kim jesteś? ',
      choices: [
        'Kuka',
        'mies',
        'sauna',
        'olet',
        'sinä',
        'Terve',
        'Onnea',
        'hän',
      ],
      correctAnswer: 'Terve kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim ona jest?',
      choices: ['lapsi', ' kuka', ' on', ' Anteeksi', ' mies', ' hän', ' sinä'],
      correctAnswer: 'Anteeksi, kuka hän on',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim jesteś?',
      choices: [
        'Anteeksi',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'tanssin',
        'Pari',
        'nyt',
        'todella',
      ],
      correctAnswer: 'Anteeksi kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Finlandia jest zawsze piękna',
      choices: [
        'nainen',
        ' aina',
        ' Anteeksi',
        ' on',
        ' kaunis',
        'Suomi',
        ' todella',
        ' sinä',
      ],
      correctAnswer: 'Suomi on aina kaunis',
    },

    {
      type: 'single-choice',
      question: 'Mężczyzna',
      choices: ['nainen', ' paljon', ' tanssin', ' väinö', ' mies'],
      correctAnswer: 'mies ',
    },

    {
      type: 'single-choice',
      question: 'przystojny',
      choices: ['kaunis', ' komea', ' kota', ' hauska', ' onnea', ' todella'],
      correctAnswer: 'komea',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Otso',
      choices: [
        'Pyry',
        'Otso',
        'olemee',
        'olen',
        ' kuka',
        'Terve',
        'sinä',
        'olet',
        'Minä',
        '',
      ],
      correctAnswer: 'Minä olen Pyry',
    },

    {
      type: 'single-choice',
      question: 'Anteeksi',
      choices: ['Dziękuje', ' Przepraszam', ' Narazie', ' Cześć', ' Usiądź'],
      correctAnswer: 'Przepraszam',
    },

    {
      type: 'single-choice',
      question: 'Nainen',
      choices: ['nie', ' mężczyzna', ' kobieta', ' dziecko', 'nie wiem'],
      correctAnswer: 'kobieta',
    },

    {
      type: 'create-sentence',
      question: 'Pyry, jesteś zabawny',
      choices: [
        'Onnea',
        'Pyry',
        'sinä',
        'olen',
        'olet',
        'lapsi',
        'hauska',
        'aina',
        'paljon',
      ],
      correctAnswer: 'Pyry sinä olet hauska',
    },

    {
      type: 'create-sentence',
      question: 'Kippis ja paljon onnea!',
      choices: [
        'Cześć',
        ' Jestem',
        ' Zdrowie',
        ' ja',
        ' ona',
        ' pije',
        ' Witam',
        ' powodzenia',
        ' i',
      ],
      correctAnswer: 'Zdrowie i powodzenia',
    },

    {
      type: 'single-choice',
      question: 'Witam!',
      choices: ['Terve', 'Tervetuloa', 'Onnea', 'Otso', 'olemee'],
      correctAnswer: 'Tervetuloa',
    },

    {
      type: 'create-sentence',
      question: 'Jej! Powodzenia!',
      choices: ['Anteeksi', 'Onnea', 'Sinä', 'olet', 'tanssin', 'Pari', 'Jee'],
      correctAnswer: 'Jee Onnea',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Elsa',
      choices: [
        'Elsa',
        'Terve',
        'Tervetuloa',
        'Onnea',
        'Minä',
        'olemee',
        'olen',
      ],
      correctAnswer: 'Minä olen Elsa',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim jesteś?',
      choices: [
        'Anteeksi',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'tanssin',
        'Pari',
        'nyt',
        'todella',
      ],
      correctAnswer: 'Anteeksi kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Finlandia jest zawsze piękna',
      choices: [
        'nainen',
        ' aina',
        ' Anteeksi',
        ' on',
        ' kaunis',
        'Suomi',
        ' todella',
        ' sinä',
      ],
      correctAnswer: 'Suomi on aina kaunis',
    },

    {
      type: 'single-choice',
      question: 'Cześć!',
      choices: ['Elsa', 'Terve', 'Tervetuloa', 'Onnea'],
      correctAnswer: 'Terve',
    },

    {
      type: 'create-sentence',
      question: 'Cześć! Kim jesteś? ',
      choices: [
        'Kuka',
        'mies',
        'sauna',
        'olet',
        'sinä',
        'Terve',
        'Onnea',
        'hän',
      ],
      correctAnswer: 'Terve kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Otso',
      choices: ['Terve', 'Onnea', 'Otso', 'olemee', 'Minä', 'olen'],
      correctAnswer: 'Minä olen Otso',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim jesteś?',
      choices: [
        'Anteeksi',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'tanssin',
        'Pari',
        'nyt',
        'todella',
      ],
      correctAnswer: 'Anteeksi kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Elsa',
      choices: [
        'Elsa',
        'Terve',
        'Tervetuloa',
        'Onnea',
        'Minä',
        'olemee',
        'olen',
      ],
      correctAnswer: 'Minä olen Elsa',
    },

    {
      type: 'single-choice',
      question: 'Witam!',
      choices: ['Terve', 'Tervetuloa', 'Onnea', 'Otso', 'olemee'],
      correctAnswer: 'Tervetuloa',
    },

    {
      type: 'create-sentence',
      question: 'Jej! Powodzenia!',
      choices: ['Anteeksi', 'Onnea', 'Sinä', 'olet', 'tanssin', 'Pari', 'Jee'],
      correctAnswer: 'Jee Onnea',
    },

    {
      type: 'create-sentence',
      question: 'Pyry, jesteś zabawny',
      choices: [
        'Onnea',
        'Pyry',
        'sinä',
        'olen',
        'olet',
        'lapsi',
        'hauska',
        'aina',
        'paljon',
      ],
      correctAnswer: 'Pyry sinä olet hauska',
    },

    {
      type: 'create-sentence',
      question: 'Kippis ja paljon onnea!',
      choices: [
        'Cześć',
        ' Jestem',
        ' Zdrowie',
        ' ja',
        ' ona',
        ' pije',
        ' Witam',
        ' powodzenia',
        ' i',
      ],
      correctAnswer: 'Zdrowie i powodzenia',
    },

    {
      type: 'create-sentence',
      question: 'Zdrowie i powodzenia!',
      choices: [
        'ja',
        'Kippis',
        ' lapsi',
        ' väinö',
        ' mies',
        ' hauska',
        ' onnea',
        ' sinä',
        ' olen',
        ' paljon',
      ],
      correctAnswer: 'Kippis ja paljon onnea',
    },

    {
      type: 'single-choice',
      question: 'Nainen',
      choices: ['nie', ' mężczyzna', ' kobieta', ' dziecko', 'nie wiem'],
      correctAnswer: 'kobieta',
    },

    {
      type: 'create-sentence',
      question: 'Elsa on nainen',
      choices: [
        'Otso',
        ' ma',
        ' Elsa',
        ' dzieckiem',
        ' kobietą',
        ' nie',
        ' jest',
      ],
      correctAnswer: 'Elsa jest kobietą',
    },

    {
      type: 'create-sentence',
      question: 'Kuba on mies',
      choices: [
        'miesiąc',
        ' Kuba',
        ' ma',
        ' mężczyzną ',
        'miejsce',
        ' robi',
        ' jest',
      ],
      correctAnswer: 'Kuba jest mężczyzną',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Otso',
      choices: [
        'Pyry',
        'Otso',
        'olemee',
        'olen',
        ' kuka',
        'Terve',
        'sinä',
        'olet',
        'Minä',
        '',
      ],
      correctAnswer: 'Minä olen Pyry',
    },

    {
      type: 'single-choice',
      question: 'Anteeksi',
      choices: ['Dziękuje', ' Przepraszam', ' Narazie', ' Cześć', ' Usiądź'],
      correctAnswer: 'Przepraszam',
    },

    {
      type: 'single-choice',
      question: 'Dziecko',
      choices: ['lapsi', ' väinö', ' mies', ' hauska', ' onnea', ' sinä '],
      correctAnswer: 'lapsi',
    },

    {
      type: 'create-sentence',
      question: 'Kuka hän on?',
      choices: ['Kim', ' Co', ' to', ' jest', ' Gdzie', ' ona', ' Jakie'],
      correctAnswer: 'Kim ona jest',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim ona jest?',
      choices: ['lapsi', ' kuka', ' on', ' Anteeksi', ' mies', ' hän', ' sinä'],
      correctAnswer: 'Anteeksi, kuka hän on',
    },

    {
      type: 'single-choice',
      question: 'Mężczyzna',
      choices: ['nainen', ' paljon', ' tanssin', ' väinö', ' mies'],
      correctAnswer: 'mies ',
    },

    {
      type: 'single-choice',
      question: 'przystojny',
      choices: ['kaunis', ' komea', ' kota', ' hauska', ' onnea', ' todella'],
      correctAnswer: 'komea',
    },

    {
      type: 'single-choice',
      question: 'Finlandia',
      choices: ['Fin', ' Pari', ' Suomi', ' Aina', ' Tervetuloa'],
      correctAnswer: 'Suomi',
    },

    {
      type: 'single-choice',
      question: 'Aina',
      choices: ['zabawny', ' pierwszy', ' znowu', ' zawsze', ' wiem '],
      correctAnswer: 'zawsze',
    },

    {
      type: 'create-sentence',
      question: 'Finlandia jest zawsze piękna',
      choices: [
        'nainen',
        ' aina',
        ' Anteeksi',
        ' on',
        ' kaunis',
        'Suomi',
        ' todella',
        ' sinä',
      ],
      correctAnswer: 'Suomi on aina kaunis',
    },

    {
      type: 'create-sentence',
      question: 'Sinä olet todella komea',
      choices: [
        'naprawde',
        ' Witam',
        ' Dziękuje',
        ' przystojny',
        ' piękna',
        ' Jesteś',
        ' pije ',
      ],
      correctAnswer: 'Jesteś naprawde przystojny',
    },

    {
      type: 'single-choice',
      question: 'Cześć!',
      choices: ['Elsa', 'Terve', 'Tervetuloa', 'Onnea'],
      correctAnswer: 'Terve',
    },

    {
      type: 'single-choice',
      question: 'Dziecko',
      choices: ['lapsi', ' väinö', ' mies', ' hauska', ' onnea', ' sinä '],
      correctAnswer: 'lapsi',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Elsa',
      choices: [
        'Elsa',
        'Terve',
        'Tervetuloa',
        'Onnea',
        'Minä',
        'olemee',
        'olen',
      ],
      correctAnswer: 'Minä olen Elsa',
    },

    {
      type: 'create-sentence',
      question: 'Cześć! Kim jesteś? ',
      choices: [
        'Kuka',
        'mies',
        'sauna',
        'olet',
        'sinä',
        'Terve',
        'Onnea',
        'hän',
      ],
      correctAnswer: 'Terve kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim ona jest?',
      choices: ['lapsi', ' kuka', ' on', ' Anteeksi', ' mies', ' hän', ' sinä'],
      correctAnswer: 'Anteeksi, kuka hän on',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim jesteś?',
      choices: [
        'Anteeksi',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'tanssin',
        'Pari',
        'nyt',
        'todella',
      ],
      correctAnswer: 'Anteeksi kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Finlandia jest zawsze piękna',
      choices: [
        'nainen',
        ' aina',
        ' Anteeksi',
        ' on',
        ' kaunis',
        'Suomi',
        ' todella',
        ' sinä',
      ],
      correctAnswer: 'Suomi on aina kaunis',
    },

    {
      type: 'single-choice',
      question: 'Mężczyzna',
      choices: ['nainen', ' paljon', ' tanssin', ' väinö', ' mies'],
      correctAnswer: 'mies ',
    },

    {
      type: 'single-choice',
      question: 'przystojny',
      choices: ['kaunis', ' komea', ' kota', ' hauska', ' onnea', ' todella'],
      correctAnswer: 'komea',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Otso',
      choices: [
        'Pyry',
        'Otso',
        'olemee',
        'olen',
        ' kuka',
        'Terve',
        'sinä',
        'olet',
        'Minä',
        '',
      ],
      correctAnswer: 'Minä olen Pyry',
    },

    {
      type: 'single-choice',
      question: 'Anteeksi',
      choices: ['Dziękuje', ' Przepraszam', ' Narazie', ' Cześć', ' Usiądź'],
      correctAnswer: 'Przepraszam',
    },

    {
      type: 'single-choice',
      question: 'Nainen',
      choices: ['nie', ' mężczyzna', ' kobieta', ' dziecko', 'nie wiem'],
      correctAnswer: 'kobieta',
    },

    {
      type: 'create-sentence',
      question: 'Pyry, jesteś zabawny',
      choices: [
        'Onnea',
        'Pyry',
        'sinä',
        'olen',
        'olet',
        'lapsi',
        'hauska',
        'aina',
        'paljon',
      ],
      correctAnswer: 'Pyry sinä olet hauska',
    },

    {
      type: 'create-sentence',
      question: 'Kippis ja paljon onnea!',
      choices: [
        'Cześć',
        ' Jestem',
        ' Zdrowie',
        ' ja',
        ' ona',
        ' pije',
        ' Witam',
        ' powodzenia',
        ' i',
      ],
      correctAnswer: 'Zdrowie i powodzenia',
    },

    {
      type: 'single-choice',
      question: 'Witam!',
      choices: ['Terve', 'Tervetuloa', 'Onnea', 'Otso', 'olemee'],
      correctAnswer: 'Tervetuloa',
    },

    {
      type: 'create-sentence',
      question: 'Jej! Powodzenia!',
      choices: ['Anteeksi', 'Onnea', 'Sinä', 'olet', 'tanssin', 'Pari', 'Jee'],
      correctAnswer: 'Jee Onnea',
    },

    {
      type: 'create-sentence',
      question: 'Jestem Elsa',
      choices: [
        'Elsa',
        'Terve',
        'Tervetuloa',
        'Onnea',
        'Minä',
        'olemee',
        'olen',
      ],
      correctAnswer: 'Minä olen Elsa',
    },

    {
      type: 'create-sentence',
      question: 'Przepraszam, kim jesteś?',
      choices: [
        'Anteeksi',
        'kuka',
        'Terve',
        'sinä',
        'olet',
        'tanssin',
        'Pari',
        'nyt',
        'todella',
      ],
      correctAnswer: 'Anteeksi kuka sinä olet',
    },

    {
      type: 'create-sentence',
      question: 'Finlandia jest zawsze piękna',
      choices: [
        'nainen',
        ' aina',
        ' Anteeksi',
        ' on',
        ' kaunis',
        'Suomi',
        ' todella',
        ' sinä',
      ],
      correctAnswer: 'Suomi on aina kaunis',
    },
  ],
  questionsTwo: [
    {
      type: 'create-sentence',
      question: 'To jest dobra sauna',
      choices: [
        'hyvä',
        ' han',
        ' ja',
        ' sauna',
        ' on',
        ' Olet',
        ' tyttö',
        ' Onko',
        ' Tämä ',
      ],
      correctAnswer: 'Tämä on hyvä sauna',
    },

    {
      type: 'single-choice',
      question: 'pies',
      choices: [
        'kaunis',
        ' kiltti',
        ' olemee',
        ' koira',
        ' aina',
        ' mies',
        ' lapsi',
      ],
      correctAnswer: 'koira',
    },

    {
      type: 'single-choice',
      question: 'cicha',
      choices: [
        'olmee',
        ' tanssin',
        ' poika',
        ' aina',
        ' rehellinen',
        ' lapsi',
        ' maa',
      ],
      correctAnswer: 'hiljainen',
    },

    {
      type: 'create-sentence',
      question: 'Tämä on hyvä sauna',
      choices: [
        'Ona',
        ' ma',
        ' jest',
        ' To',
        ' sauna',
        ' zła',
        ' zawsze',
        ' pierwszy',
        ' dobra',
      ],
      correctAnswer: 'To jest dobra sauna',
    },

    {
      type: 'create-sentence',
      question: 'Hilla on hiljainen tyttö',
      choices: [
        'ona',
        ' jest',
        ' piękną',
        ' wiem',
        ' Hilla',
        ' dzieckiem',
        ' dziewczyną',
        ' cichą',
      ],
      correctAnswer: 'Hilla jest cichą dziewczyną',
    },

    {
      type: 'create-sentence',
      question: 'Jesteś dobrą dziewczyną',
      choices: [
        'mukava',
        ' aina',
        ' kuka',
        ' Olet',
        ' tyttö',
        ' tuhma',
        ' olemee',
        ' poika',
      ],
      correctAnswer: 'Olet mukava tyttö',
    },

    {
      type: 'create-sentence',
      question: 'Olet rehellinen nainen',
      choices: [
        'Ona',
        ' jest',
        ' Jesteś',
        ' kobietą',
        ' miłą',
        ' szczerą',
        ' piękną',
      ],
      correctAnswer: 'Jesteś szczerą kobietą',
    },

    {
      type: 'single-choice',
      question: 'szczery',
      choices: [
        'olmee',
        ' tanssin',
        ' poika',
        ' aina',
        ' rehellinen',
        ' lapsi',
        ' maa',
      ],
      correctAnswer: 'rehellinen',
    },

    {
      type: 'create-sentence',
      question: 'Estonia jest mała i piękna',
      choices: [
        'Pari',
        ' ja',
        ' on',
        ' kaunis',
        ' kiltti',
        ' aina',
        ' Viro',
        ' pieni',
        ' olen',
        ' poika',
        ' rehellinen',
      ],
      correctAnswer: 'Viro on pieni ja kaunis',
    },

    {
      type: 'single-choice',
      question: 'dziewczyna ',
      choices: [
        'poika',
        ' aina',
        ' kuka',
        ' olen',
        ' tyttö',
        ' tuhma',
        ' olemee',
        ' mukava',
      ],
      correctAnswer: 'tyttö',
    },

    {
      type: 'create-sentence',
      question: 'Jakiego rodzaju to jest pies?',
      choices: [
        'Tervetuloa',
        ' olmee',
        ' koira',
        ' se',
        'tanssin',
        ' poika',
        ' aina',
        ' on',
        ' lapsi',
        ' maa',
        ' Millainen',
      ],
      correctAnswer: 'Millainen koira se on',
    },

    {
      type: 'create-sentence',
      question: 'Jesteś dobrym chłopakiem',
      choices: [
        'mukava',
        ' aina',
        ' kuka',
        ' Olet',
        ' tyttö',
        ' tuhma',
        ' olemee',
        ' poika',
      ],
      correctAnswer: 'Olet mukava poika',
    },

    {
      type: 'single-choice',
      question: 'zajączek',
      choices: [
        'kaunis',
        ' kiltti',
        ' pupu',
        ' koira',
        ' aina',
        ' mies',
        ' lapsi',
      ],
      correctAnswer: 'pupu',
    },

    {
      type: 'create-sentence',
      question: 'Ja mam zajączka',
      choices: [
        'Pari',
        ' pupu',
        ' olen',
        ' ja',
        ' on',
        ' Millainen',
        ' Minulla',
        ' pieni',
      ],
      correctAnswer: 'Minulla on pupu',
    },

    {
      type: 'create-sentence',
      question: 'To jest małe i miłe',
      choices: [
        'Olet',
        ' Se',
        ' ja',
        ' kaunis',
        ' kiltti',
        ' tanssin',
        ' pieni',
        ' on',
        ' aina',
      ],
      correctAnswer: 'Se on pieni ja kiltti',
    },

    {
      type: 'create-sentence',
      question: 'Se on pieni ja kiltti',
      choices: [
        'miłe',
        ' ty',
        ' piękne',
        ' szczere',
        ' To',
        ' Ten',
        ' jest',
        ' i',
        ' małe',
        ' znowu',
        ' mam',
      ],
      correctAnswer: 'To jest małe i miłe',
    },

    {
      type: 'single-choice',
      question: 'niegrzeczny',
      choices: [
        'olmee',
        ' tanssin',
        ' poika',
        ' aina',
        ' rehellinen',
        ' lapsi',
        ' maa',
        ' tuhma',
      ],
      correctAnswer: 'tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Ten kot jest niegrzeczny!',
      choices: [
        'Tämä',
        ' kiltti',
        ' tuhma',
        ' ty',
        ' ja',
        ' Aina',
        ' kissa',
        ' aina',
        ' Terve',
        ' on',
      ],
      correctAnswer: 'Tämä kissa on tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Hänellä on sininen käärme',
      choices: [
        'On',
        ' Dziecko',
        ' czerwonego',
        ' zajączka',
        ' węża',
        ' ma',
        ' nie ma',
        ' niebieskiego',
        ' Ona',
      ],
      correctAnswer: 'Ona ma niebieskiego węża',
    },

    {
      type: 'single-choice',
      question: 'sininen',
      choices: [
        'niebieski',
        ' czerwony',
        ' żółty',
        ' zielony',
        ' brązowy',
        ' czarny',
      ],
      correctAnswer: 'niebieski',
    },

    {
      type: 'single-choice',
      question: 'Estonia',
      choices: ['Estonia', ' Estania', ' Suomi', ' Pari', ' Viro', ' Ruotsi'],
      correctAnswer: 'Viro',
    },

    {
      type: 'create-sentence',
      question: 'Jakim krajem jest Estonia',
      choices: [
        'Tervetuloa',
        ' Minulla',
        ' ja',
        ' to',
        ' Millainen',
        ' maa',
        ' Viro',
        ' on',
        ' aina',
        ' han',
        ' hän',
      ],
      correctAnswer: 'Millainen maa Viro on?',
    },

    {
      type: 'create-sentence',
      question: 'Viro on pieni ja kaunis',
      choices: [
        'Szwecja',
        ' Finlandia',
        ' piękna',
        ' była',
        ' jest',
        ' też',
        ' zawsze',
        ' i',
        ' mała',
        ' Estonia',
      ],
      correctAnswer: 'Estonia jest mała i piękna',
    },

    {
      type: 'create-sentence',
      question: 'Czy Szwecja jest zimnym krajem?',
      choices: [
        'Ruotsi',
        ' Suomi',
        ' paljon',
        ' kaunis',
        ' kylmä',
        ' maa',
        ' ma',
        ' Olet',
        ' Onko',
        ' tanssin',
        ' rehellinen',
      ],
      correctAnswer: 'Onko Ruotsi kylmä maa',
    },

    {
      type: 'single-choice',
      question: 'Ruotsi',
      choices: [
        'Estonia',
        ' Przepraszam',
        ' wiem',
        ' wąż',
        ' pies',
        ' kobieta',
        ' Szwecja',
        ' Polska',
        ' dziecko',
      ],
      correctAnswer: 'Szwecja',
    },

    {
      type: 'create-sentence',
      question: 'Millainen koira se on?',
      choices: [
        'Jakiego',
        ' Jakim',
        ' pies',
        ' robi',
        ' Kto',
        ' jest',
        ' on',
        ' to',
        ' rodzaju',
        '',
      ],
      correctAnswer: 'Jakiego rodzaju to jest pies',
    },

    {
      type: 'create-sentence',
      question: 'To jest dobra sauna',
      choices: [
        'hyvä',
        ' han',
        ' ja',
        ' sauna',
        ' on',
        ' Olet',
        ' tyttö',
        ' Onko',
        ' Tämä ',
      ],
      correctAnswer: 'Tämä on hyvä sauna',
    },

    {
      type: 'single-choice',
      question: 'pies',
      choices: [
        'kaunis',
        ' kiltti',
        ' olemee',
        ' koira',
        ' aina',
        ' mies',
        ' lapsi',
      ],
      correctAnswer: 'koira',
    },

    {
      type: 'single-choice',
      question: 'cicha',
      choices: [
        'olmee',
        ' tanssin',
        ' poika',
        ' aina',
        ' rehellinen',
        ' lapsi',
        ' maa',
      ],
      correctAnswer: 'hiljainen',
    },

    {
      type: 'create-sentence',
      question: 'Tämä on hyvä sauna',
      choices: [
        'Ona',
        ' ma',
        ' jest',
        ' To',
        ' sauna',
        ' zła',
        ' zawsze',
        ' pierwszy',
        ' dobra',
      ],
      correctAnswer: 'To jest dobra sauna',
    },

    {
      type: 'create-sentence',
      question: 'Hilla on hiljainen tyttö',
      choices: [
        'ona',
        ' jest',
        ' piękną',
        ' wiem',
        ' Hilla',
        ' dzieckiem',
        ' dziewczyną',
        ' cichą',
      ],
      correctAnswer: 'Hilla jest cichą dziewczyną',
    },

    {
      type: 'create-sentence',
      question: 'Jesteś dobrą dziewczyną',
      choices: [
        'mukava',
        ' aina',
        ' kuka',
        ' Olet',
        ' tyttö',
        ' tuhma',
        ' olemee',
        ' poika',
      ],
      correctAnswer: 'Olet mukava tyttö',
    },

    {
      type: 'create-sentence',
      question: 'Olet rehellinen nainen',
      choices: [
        'Ona',
        ' jest',
        ' Jesteś',
        ' kobietą',
        ' miłą',
        ' szczerą',
        ' piękną',
      ],
      correctAnswer: 'Jesteś szczerą kobietą',
    },

    {
      type: 'single-choice',
      question: 'szczery',
      choices: [
        'olmee',
        ' tanssin',
        ' poika',
        ' aina',
        ' rehellinen',
        ' lapsi',
        ' maa',
      ],
      correctAnswer: 'rehellinen',
    },

    {
      type: 'create-sentence',
      question: 'Estonia jest mała i piękna',
      choices: [
        'Pari',
        ' ja',
        ' on',
        ' kaunis',
        ' kiltti',
        ' aina',
        ' Viro',
        ' pieni',
        ' olen',
        ' poika',
        ' rehellinen',
      ],
      correctAnswer: 'Viro on pieni ja kaunis',
    },

    {
      type: 'single-choice',
      question: 'dziewczyna ',
      choices: [
        'poika',
        ' aina',
        ' kuka',
        ' olen',
        ' tyttö',
        ' tuhma',
        ' olemee',
        ' mukava',
      ],
      correctAnswer: 'tyttö',
    },

    {
      type: 'create-sentence',
      question: 'Jakiego rodzaju to jest pies?',
      choices: [
        'Tervetuloa',
        ' olmee',
        ' koira',
        ' se',
        'tanssin',
        ' poika',
        ' aina',
        ' on',
        ' lapsi',
        ' maa',
        ' Millainen',
      ],
      correctAnswer: 'Millainen koira se on',
    },

    {
      type: 'create-sentence',
      question: 'Jesteś dobrym chłopakiem',
      choices: [
        'mukava',
        ' aina',
        ' kuka',
        ' Olet',
        ' tyttö',
        ' tuhma',
        ' olemee',
        ' poika',
      ],
      correctAnswer: 'Olet mukava poika',
    },

    {
      type: 'single-choice',
      question: 'zajączek',
      choices: [
        'kaunis',
        ' kiltti',
        ' pupu',
        ' koira',
        ' aina',
        ' mies',
        ' lapsi',
      ],
      correctAnswer: 'pupu',
    },

    {
      type: 'create-sentence',
      question: 'Ja mam zajączka',
      choices: [
        'Pari',
        ' pupu',
        ' olen',
        ' ja',
        ' on',
        ' Millainen',
        ' Minulla',
        ' pieni',
      ],
      correctAnswer: 'Minulla on pupu',
    },

    {
      type: 'create-sentence',
      question: 'To jest małe i miłe',
      choices: [
        'Olet',
        ' Se',
        ' ja',
        ' kaunis',
        ' kiltti',
        ' tanssin',
        ' pieni',
        ' on',
        ' aina',
      ],
      correctAnswer: 'Se on pieni ja kiltti',
    },

    {
      type: 'create-sentence',
      question: 'Se on pieni ja kiltti',
      choices: [
        'miłe',
        ' ty',
        ' piękne',
        ' szczere',
        ' To',
        ' Ten',
        ' jest',
        ' i',
        ' małe',
        ' znowu',
        ' mam',
      ],
      correctAnswer: 'To jest małe i miłe',
    },

    {
      type: 'single-choice',
      question: 'niegrzeczny',
      choices: [
        'olmee',
        ' tanssin',
        ' poika',
        ' aina',
        ' rehellinen',
        ' lapsi',
        ' maa',
        ' tuhma',
      ],
      correctAnswer: 'tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Ten kot jest niegrzeczny!',
      choices: [
        'Tämä',
        ' kiltti',
        ' tuhma',
        ' ty',
        ' ja',
        ' Aina',
        ' kissa',
        ' aina',
        ' Terve',
        ' on',
      ],
      correctAnswer: 'Tämä kissa on tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Hänellä on sininen käärme',
      choices: [
        'On',
        ' Dziecko',
        ' czerwonego',
        ' zajączka',
        ' węża',
        ' ma',
        ' nie ma',
        ' niebieskiego',
        ' Ona',
      ],
      correctAnswer: 'Ona ma niebieskiego węża',
    },

    {
      type: 'single-choice',
      question: 'sininen',
      choices: [
        'niebieski',
        ' czerwony',
        ' żółty',
        ' zielony',
        ' brązowy',
        ' czarny',
      ],
      correctAnswer: 'niebieski',
    },

    {
      type: 'single-choice',
      question: 'Estonia',
      choices: ['Estonia', ' Estania', ' Suomi', ' Pari', ' Viro', ' Ruotsi'],
      correctAnswer: 'Viro',
    },

    {
      type: 'create-sentence',
      question: 'Jakim krajem jest Estonia',
      choices: [
        'Tervetuloa',
        ' Minulla',
        ' ja',
        ' to',
        ' Millainen',
        ' maa',
        ' Viro',
        ' on',
        ' aina',
        ' han',
        ' hän',
      ],
      correctAnswer: 'Millainen maa Viro on?',
    },

    {
      type: 'create-sentence',
      question: 'Viro on pieni ja kaunis',
      choices: [
        'Szwecja',
        ' Finlandia',
        ' piękna',
        ' była',
        ' jest',
        ' też',
        ' zawsze',
        ' i',
        ' mała',
        ' Estonia',
      ],
      correctAnswer: 'Estonia jest mała i piękna',
    },

    {
      type: 'create-sentence',
      question: 'Czy Szwecja jest zimnym krajem?',
      choices: [
        'Ruotsi',
        ' Suomi',
        ' paljon',
        ' kaunis',
        ' kylmä',
        ' maa',
        ' ma',
        ' Olet',
        ' Onko',
        ' tanssin',
        ' rehellinen',
      ],
      correctAnswer: 'Onko Ruotsi kylmä maa',
    },

    {
      type: 'single-choice',
      question: 'Ruotsi',
      choices: [
        'Estonia',
        ' Przepraszam',
        ' wiem',
        ' wąż',
        ' pies',
        ' kobieta',
        ' Szwecja',
        ' Polska',
        ' dziecko',
      ],
      correctAnswer: 'Szwecja',
    },

    {
      type: 'create-sentence',
      question: 'Millainen koira se on?',
      choices: [
        'Jakiego',
        ' Jakim',
        ' pies',
        ' robi',
        ' Kto',
        ' jest',
        ' on',
        ' to',
        ' rodzaju',
        '',
      ],
      correctAnswer: 'Jakiego rodzaju to jest pies',
    },

    {
      type: 'create-sentence',
      question: 'Ja mam zajączka',
      choices: [
        'Pari',
        ' pupu',
        ' olen',
        ' ja',
        ' on',
        ' Millainen',
        ' Minulla',
        ' pieni',
      ],
      correctAnswer: 'Minulla on pupu',
    },

    {
      type: 'create-sentence',
      question: 'To jest małe i miłe',
      choices: [
        'Olet',
        ' Se',
        ' ja',
        ' kaunis',
        ' kiltti',
        ' tanssin',
        ' pieni',
        ' on',
        ' aina',
      ],
      correctAnswer: 'Se on pieni ja kiltti',
    },

    {
      type: 'create-sentence',
      question: 'Se on pieni ja kiltti',
      choices: [
        'miłe',
        ' ty',
        ' piękne',
        ' szczere',
        ' To',
        ' Ten',
        ' jest',
        ' i',
        ' małe',
        ' znowu',
        ' mam',
      ],
      correctAnswer: 'To jest małe i miłe',
    },

    {
      type: 'single-choice',
      question: 'niegrzeczny',
      choices: [
        'olmee',
        ' tanssin',
        ' poika',
        ' aina',
        ' rehellinen',
        ' lapsi',
        ' maa',
        ' tuhma',
      ],
      correctAnswer: 'tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Ten kot jest niegrzeczny!',
      choices: [
        'Tämä',
        ' kiltti',
        ' tuhma',
        ' ty',
        ' ja',
        ' Aina',
        ' kissa',
        ' aina',
        ' Terve',
        ' on',
      ],
      correctAnswer: 'Tämä kissa on tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Hänellä on sininen käärme',
      choices: [
        'On',
        ' Dziecko',
        ' czerwonego',
        ' zajączka',
        ' węża',
        ' ma',
        ' nie ma',
        ' niebieskiego',
        ' Ona',
      ],
      correctAnswer: 'Ona ma niebieskiego węża',
    },

    {
      type: 'single-choice',
      question: 'sininen',
      choices: [
        'niebieski',
        ' czerwony',
        ' żółty',
        ' zielony',
        ' brązowy',
        ' czarny',
      ],
      correctAnswer: 'niebieski',
    },

    {
      type: 'single-choice',
      question: 'Estonia',
      choices: ['Estonia', ' Estania', ' Suomi', ' Pari', ' Viro', ' Ruotsi'],
      correctAnswer: 'Viro',
    },

    {
      type: 'create-sentence',
      question: 'Jakim krajem jest Estonia',
      choices: [
        'Tervetuloa',
        ' Minulla',
        ' ja',
        ' to',
        ' Millainen',
        ' maa',
        ' Viro',
        ' on',
        ' aina',
        ' han',
        ' hän',
      ],
      correctAnswer: 'Millainen maa Viro on?',
    },

    {
      type: 'create-sentence',
      question: 'Viro on pieni ja kaunis',
      choices: [
        'Szwecja',
        ' Finlandia',
        ' piękna',
        ' była',
        ' jest',
        ' też',
        ' zawsze',
        ' i',
        ' mała',
        ' Estonia',
      ],
      correctAnswer: 'Estonia jest mała i piękna',
    },

    {
      type: 'create-sentence',
      question: 'Czy Szwecja jest zimnym krajem?',
      choices: [
        'Ruotsi',
        ' Suomi',
        ' paljon',
        ' kaunis',
        ' kylmä',
        ' maa',
        ' ma',
        ' Olet',
        ' Onko',
        ' tanssin',
        ' rehellinen',
      ],
      correctAnswer: 'Onko Ruotsi kylmä maa',
    },

    {
      type: 'single-choice',
      question: 'Ruotsi',
      choices: [
        'Estonia',
        ' Przepraszam',
        ' wiem',
        ' wąż',
        ' pies',
        ' kobieta',
        ' Szwecja',
        ' Polska',
        ' dziecko',
      ],
      correctAnswer: 'Szwecja',
    },

    {
      type: 'create-sentence',
      question: 'Millainen koira se on?',
      choices: [
        'Jakiego',
        ' Jakim',
        ' pies',
        ' robi',
        ' Kto',
        ' jest',
        ' on',
        ' to',
        ' rodzaju',
        '',
      ],
      correctAnswer: 'Jakiego rodzaju to jest pies',
    },

    {
      type: 'create-sentence',
      question: 'To jest dobra sauna',
      choices: [
        'hyvä',
        ' han',
        ' ja',
        ' sauna',
        ' on',
        ' Olet',
        ' tyttö',
        ' Onko',
        ' Tämä ',
      ],
      correctAnswer: 'Tämä on hyvä sauna',
    },

    {
      type: 'single-choice',
      question: 'pies',
      choices: [
        'kaunis',
        ' kiltti',
        ' olemee',
        ' koira',
        ' aina',
        ' mies',
        ' lapsi',
      ],
      correctAnswer: 'koira',
    },

    {
      type: 'single-choice',
      question: 'cicha',
      choices: [
        'olmee',
        ' tanssin',
        ' poika',
        ' aina',
        ' rehellinen',
        ' lapsi',
        ' maa',
      ],
      correctAnswer: 'hiljainen',
    },

    {
      type: 'create-sentence',
      question: 'Tämä on hyvä sauna',
      choices: [
        'Ona',
        ' ma',
        ' jest',
        ' To',
        ' sauna',
        ' zła',
        ' zawsze',
        ' pierwszy',
        ' dobra',
      ],
      correctAnswer: 'To jest dobra sauna',
    },

    {
      type: 'create-sentence',
      question: 'Hilla on hiljainen tyttö',
      choices: [
        'ona',
        ' jest',
        ' piękną',
        ' wiem',
        ' Hilla',
        ' dzieckiem',
        ' dziewczyną',
        ' cichą',
      ],
      correctAnswer: 'Hilla jest cichą dziewczyną',
    },

    {
      type: 'create-sentence',
      question: 'Jesteś dobrą dziewczyną',
      choices: [
        'mukava',
        ' aina',
        ' kuka',
        ' Olet',
        ' tyttö',
        ' tuhma',
        ' olemee',
        ' poika',
      ],
      correctAnswer: 'Olet mukava tyttö',
    },

    {
      type: 'create-sentence',
      question: 'Olet rehellinen nainen',
      choices: [
        'Ona',
        ' jest',
        ' Jesteś',
        ' kobietą',
        ' miłą',
        ' szczerą',
        ' piękną',
      ],
      correctAnswer: 'Jesteś szczerą kobietą',
    },

    {
      type: 'single-choice',
      question: 'szczery',
      choices: [
        'olmee',
        ' tanssin',
        ' poika',
        ' aina',
        ' rehellinen',
        ' lapsi',
        ' maa',
      ],
      correctAnswer: 'rehellinen',
    },

    {
      type: 'create-sentence',
      question: 'Estonia jest mała i piękna',
      choices: [
        'Pari',
        ' ja',
        ' on',
        ' kaunis',
        ' kiltti',
        ' aina',
        ' Viro',
        ' pieni',
        ' olen',
        ' poika',
        ' rehellinen',
      ],
      correctAnswer: 'Viro on pieni ja kaunis',
    },

    {
      type: 'single-choice',
      question: 'dziewczyna ',
      choices: [
        'poika',
        ' aina',
        ' kuka',
        ' olen',
        ' tyttö',
        ' tuhma',
        ' olemee',
        ' mukava',
      ],
      correctAnswer: 'tyttö',
    },

    {
      type: 'create-sentence',
      question: 'Jakiego rodzaju to jest pies?',
      choices: [
        'Tervetuloa',
        ' olmee',
        ' koira',
        ' se',
        'tanssin',
        ' poika',
        ' aina',
        ' on',
        ' lapsi',
        ' maa',
        ' Millainen',
      ],
      correctAnswer: 'Millainen koira se on',
    },

    {
      type: 'create-sentence',
      question: 'Jesteś dobrym chłopakiem',
      choices: [
        'mukava',
        ' aina',
        ' kuka',
        ' Olet',
        ' tyttö',
        ' tuhma',
        ' olemee',
        ' poika',
      ],
      correctAnswer: 'Olet mukava poika',
    },

    {
      type: 'single-choice',
      question: 'zajączek',
      choices: [
        'kaunis',
        ' kiltti',
        ' pupu',
        ' koira',
        ' aina',
        ' mies',
        ' lapsi',
      ],
      correctAnswer: 'pupu',
    },

    {
      type: 'create-sentence',
      question: 'Ja mam zajączka',
      choices: [
        'Pari',
        ' pupu',
        ' olen',
        ' ja',
        ' on',
        ' Millainen',
        ' Minulla',
        ' pieni',
      ],
      correctAnswer: 'Minulla on pupu',
    },

    {
      type: 'create-sentence',
      question: 'To jest małe i miłe',
      choices: [
        'Olet',
        ' Se',
        ' ja',
        ' kaunis',
        ' kiltti',
        ' tanssin',
        ' pieni',
        ' on',
        ' aina',
      ],
      correctAnswer: 'Se on pieni ja kiltti',
    },

    {
      type: 'create-sentence',
      question: 'Se on pieni ja kiltti',
      choices: [
        'miłe',
        ' ty',
        ' piękne',
        ' szczere',
        ' To',
        ' Ten',
        ' jest',
        ' i',
        ' małe',
        ' znowu',
        ' mam',
      ],
      correctAnswer: 'To jest małe i miłe',
    },

    {
      type: 'single-choice',
      question: 'niegrzeczny',
      choices: [
        'olmee',
        ' tanssin',
        ' poika',
        ' aina',
        ' rehellinen',
        ' lapsi',
        ' maa',
        ' tuhma',
      ],
      correctAnswer: 'tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Ten kot jest niegrzeczny!',
      choices: [
        'Tämä',
        ' kiltti',
        ' tuhma',
        ' ty',
        ' ja',
        ' Aina',
        ' kissa',
        ' aina',
        ' Terve',
        ' on',
      ],
      correctAnswer: 'Tämä kissa on tuhma',
    },

    {
      type: 'create-sentence',
      question: 'Hänellä on sininen käärme',
      choices: [
        'On',
        ' Dziecko',
        ' czerwonego',
        ' zajączka',
        ' węża',
        ' ma',
        ' nie ma',
        ' niebieskiego',
        ' Ona',
      ],
      correctAnswer: 'Ona ma niebieskiego węża',
    },

    {
      type: 'single-choice',
      question: 'sininen',
      choices: [
        'niebieski',
        ' czerwony',
        ' żółty',
        ' zielony',
        ' brązowy',
        ' czarny',
      ],
      correctAnswer: 'niebieski',
    },
  ],
  questionsThree: [
    {
      type: 'create-sentence',
      question: 'Missä kaupunki on?',
      choices: [
        'Meillä',
        ' Terve',
        ' Missä',
        ' te',
        ' ja',
        ' on',
        ' kiltti',
        ' kaupunki',
        ' kissa',
      ],
      correctAnswer: 'Gdzie jest miasto',
    },

    {
      type: 'single-choice',
      question: 'Gdzie',
      choices: [
        'tämä',
        ' minä',
        ' fin',
        ' missä',
        ' viro',
        ' millainen',
        ' nainen',
      ],
      correctAnswer: 'missä',
    },

    {
      type: 'create-sentence',
      question: 'Piękna piosenka jest rosyjska ',
      choices: [
        'laulu',
        ' lapsi',
        ' viro',
        ' Ruotsi',
        ' Kaunis',
        ' to',
        ' on',
        ' venäläinen',
        ' mies',
      ],
      correctAnswer: 'Kaunis laulu on venäläinen',
    },

    {
      type: 'create-sentence',
      question: 'Kaunis laulu on venäläinen',
      choices: [
        'kot',
        ' jest',
        ' szwecja',
        ' tańcze',
        ' Miła',
        ' rosyjska',
        ' piosenka',
        ' Piękna',
        ' też ',
      ],
      correctAnswer: 'Piękna piosenka jest rosyjska',
    },

    {
      type: 'single-choice',
      question: 'venäläinen',
      choices: [
        'rosyjska',
        ' Szwecja',
        ' dziewczyna',
        ' pierwszy',
        ' wiem',
        ' brązowy',
        ' rzadko',
      ],
      correctAnswer: 'rosyjska',
    },

    {
      type: 'create-sentence',
      question: 'Oletteko te nyt pari?',
      choices: [
        'Powodzenia',
        ' i',
        ' Przepraszam',
        ' zawsze',
        ' teraz',
        ' parą',
        ' Jesteście',
        ' Jesteśmy',
      ],
      correctAnswer: 'Jesteście teraz parą',
    },

    {
      type: 'single-choice',
      question: 'teraz',
      choices: [
        'pari',
        ' talo',
        ' yhdessä',
        ' usein ',
        'istuvat',
        ' olen',
        ' olemee',
        ' lapsi',
        ' nyt',
      ],
      correctAnswer: 'nyt',
    },

    {
      type: 'create-sentence',
      question: 'Ja tańcze',
      choices: [
        'Sinä',
        ' ja ',
        ' ma',
        ' aina',
        ' tanssin',
        ' maa',
        ' Meillä',
        ' Minä',
        ' Pyry',
        ' millainen',
      ],
      correctAnswer: 'Minä tanssin',
    },

    {
      type: 'single-choice',
      question: 'tanssin',
      choices: [
        'teraz',
        ' używać',
        ' tygrys',
        ' jutro',
        ' tańczyć',
        ' telewizja',
        ' zabawny',
      ],
      correctAnswer: 'tańczyć',
    },

    {
      type: 'create-sentence',
      question: 'Me olemme naimisissa',
      choices: [
        'Teraz',
        ' kaunis',
        ' małżeństwem',
        ' lubie',
        ' robie',
        ' fikołka',
        ' Jesteśmy',
        ' Też',
      ],
      correctAnswer: 'Jesteśmy małżeństwem',
    },

    {
      type: 'create-sentence',
      question: 'He istuvat yhdessä',
      choices: [
        'On',
        ' Ty',
        ' siedzisz',
        ' sam',
        ' parą',
        ' razem',
        ' są',
        ' Oni',
        ' siedzą',
        ' radio',
      ],
      correctAnswer: 'Oni siedzą razem',
    },

    {
      type: 'single-choice',
      question: 'istuvat',
      choices: [
        'tańczyć',
        ' pies',
        ' kot',
        ' kobieta',
        ' robić',
        ' siedzą',
        ' gotować',
      ],
      correctAnswer: 'siedzą',
    },

    {
      type: 'create-sentence',
      question: 'Oni siedzą razem',
      choices: [
        'Sinä',
        ' Olet',
        ' itket',
        ' istuvat',
        ' He',
        ' rehellinen',
        ' yhdessä',
        ' usein',
      ],
      correctAnswer: 'He istuvat yhdessä',
    },

    {
      type: 'create-sentence',
      question: 'Missä te seisotte?',
      choices: [
        'Co',
        ' Jak',
        ' robisz',
        ' tańczysz',
        ' siedzisz',
        ' Kim',
        ' jesteś',
        ' Gdzie',
        ' stoisz',
      ],
      correctAnswer: 'Gdzie stoisz',
    },

    {
      type: 'create-sentence',
      question: 'Ty rzadko płaczesz i często się śmiejesz',
      choices: [
        'usein',
        ' Ja',
        ' itket',
        ' Minulla',
        ' pari',
        ' aina',
        ' Sinä',
        ' fin',
        ' ja',
        ' to',
        ' harvoin',
        ' naurat',
      ],
      correctAnswer: 'Sinä itket harvoin ja naurat usein',
    },

    {
      type: 'create-sentence',
      question: 'Sinä itket harvoin ja naurat usein',
      choices: [
        'My',
        ' często',
        ' tańczymy',
        ' i',
        ' nie',
        ' używamy',
        ' Ty',
        ' rzadko',
        ' śmiejesz',
        ' się',
        ' płaczesz',
      ],
      correctAnswer: 'Ty rzadko płaczesz i często się śmiejesz',
    },

    {
      type: 'single-choice',
      question: 'płakać',
      choices: [
        'hauska',
        ' tanssin',
        ' paljon',
        ' harvoin',
        ' rehellinen',
        ' millainen',
        ' teillä',
      ],
      correctAnswer: 'harvoin',
    },

    {
      type: 'create-sentence',
      question: 'Minulla on uusi lelu',
      choices: [
        'Masz',
        ' radio',
        ' zajączka',
        ' starą',
        ' nową',
        ' Mam',
        ' zabawke',
        ' Ona',
        ' ma',
      ],
      correctAnswer: 'Mam nową zabawke',
    },

    {
      type: 'single-choice',
      question: 'uusi',
      choices: [
        'teraz',
        ' piękny',
        ' mały',
        ' nowy',
        ' dom',
        ' starą',
        ' nowa',
      ],
      correctAnswer: 'nowa',
    },

    {
      type: 'create-sentence',
      question: 'Sinulla on kaunis talo',
      choices: [
        'Mamy',
        ' wiem',
        ' telewizja',
        ' Ty',
        ' piękne',
        ' dom',
        ' piękny',
        ' masz',
        ' My',
        ' kwiaty ',
      ],
      correctAnswer: 'Ty masz piękny dom',
    },

    {
      type: 'single-choice',
      question: 'talo',
      choices: [
        'to',
        ' razem',
        ' używamy',
        ' teraz',
        ' pies',
        ' tak',
        ' dom',
        ' dobra',
      ],
      correctAnswer: 'dom',
    },

    {
      type: 'create-sentence',
      question: 'Jaką masz saune?',
      choices: [
        'on',
        'tanssin',
        ' sauna',
        ' ja',
        ' Pari',
        ' Viro',
        ' Millainen',
        ' teillä',
        ' todella',
      ],
      correctAnswer: 'Millainen sauna teillä on',
    },

    {
      type: 'create-sentence',
      question: 'Millainen sauna teillä on?',
      choices: [
        'tak',
        ' Jutro',
        ' jest',
        ' Gdzie',
        ' Jaką',
        ' saune',
        ' mamy',
        ' mała',
        ' masz',
        ' Którą',
      ],
      correctAnswer: 'Jaką masz saune',
    },

    {
      type: 'create-sentence',
      question: 'My mamy dużą saune',
      choices: [
        'Meillä',
        ' lapsi',
        ' sinä',
        ' sauna',
        ' paljon',
        ' pari',
        ' on',
        ' aina',
        ' suuri',
        ' laulu',
      ],
      correctAnswer: 'Meillä on suuri sauna',
    },

    {
      type: 'create-sentence',
      question: 'Meillä on suuri sauna',
      choices: [
        'Wy',
        ' macie',
        ' mamy',
        ' saune',
        ' waszą',
        ' mamy',
        ' piękną',
        ' szczery',
        ' dużą',
        ' My',
      ],
      correctAnswer: 'My mamy dużą saune',
    },

    {
      type: 'create-sentence',
      question: 'Heillä on radio ja televisio',
      choices: [
        'i',
        ' Oni',
        ' lubie',
        ' Ja',
        ' Wy',
        ' radio',
        ' telewizje',
        ' psa',
        ' siedzą',
        ' mają',
        ' mam',
      ],
      correctAnswer: 'Oni mają radio i telewizje',
    },

    {
      type: 'create-sentence',
      question: 'Kaunis laulu on venäläinen',
      choices: [
        'kot',
        ' jest',
        ' szwecja',
        ' tańcze',
        ' Miła',
        ' rosyjska',
        ' piosenka',
        ' Piękna',
        ' też ',
      ],
      correctAnswer: 'Piękna piosenka jest rosyjska',
    },

    {
      type: 'single-choice',
      question: 'venäläinen',
      choices: [
        'rosyjska',
        ' Szwecja',
        ' dziewczyna',
        ' pierwszy',
        ' wiem',
        ' brązowy',
        ' rzadko',
      ],
      correctAnswer: 'rosyjska',
    },

    {
      type: 'create-sentence',
      question: 'Ty rzadko płaczesz i często się śmiejesz',
      choices: [
        'usein',
        ' Ja',
        ' itket',
        ' Minulla',
        ' pari',
        ' aina',
        ' Sinä',
        ' fin',
        ' ja',
        ' to',
        ' harvoin',
        ' naurat',
      ],
      correctAnswer: 'Sinä itket harvoin ja naurat usein',
    },

    {
      type: 'create-sentence',
      question: 'Missä kaupunki on?',
      choices: [
        'Meillä',
        ' Terve',
        ' Missä',
        ' te',
        ' ja',
        ' on',
        ' kiltti',
        ' kaupunki',
        ' kissa',
      ],
      correctAnswer: 'Gdzie jest miasto',
    },

    {
      type: 'single-choice',
      question: 'Gdzie',
      choices: [
        'tämä',
        ' minä',
        ' fin',
        ' missä',
        ' viro',
        ' millainen',
        ' nainen',
      ],
      correctAnswer: 'missä',
    },

    {
      type: 'create-sentence',
      question: 'Millainen sauna teillä on?',
      choices: [
        'tak',
        ' Jutro',
        ' jest',
        ' Gdzie',
        ' Jaką',
        ' saune',
        ' mamy',
        ' mała',
        ' masz',
        ' Którą',
      ],
      correctAnswer: 'Jaką masz saune',
    },

    {
      type: 'single-choice',
      question: 'uusi',
      choices: [
        'teraz',
        ' piękny',
        ' mały',
        ' nowy',
        ' dom',
        ' starą',
        ' nowa',
      ],
      correctAnswer: 'nowa',
    },

    {
      type: 'single-choice',
      question: 'talo',
      choices: [
        'to',
        ' razem',
        ' używamy',
        ' teraz',
        ' pies',
        ' tak',
        ' dom',
        ' dobra',
      ],
      correctAnswer: 'dom',
    },

    {
      type: 'create-sentence',
      question: 'Sinulla on kaunis talo',
      choices: [
        'Mamy',
        ' wiem',
        ' telewizja',
        ' Ty',
        ' piękne',
        ' dom',
        ' piękny',
        ' masz',
        ' My',
        ' kwiaty ',
      ],
      correctAnswer: 'Ty masz piękny dom',
    },

    {
      type: 'create-sentence',
      question: 'Sinä itket harvoin ja naurat usein',
      choices: [
        'My',
        ' często',
        ' tańczymy',
        ' i',
        ' nie',
        ' używamy',
        ' Ty',
        ' rzadko',
        ' śmiejesz',
        ' się',
        ' płaczesz',
      ],
      correctAnswer: 'Ty rzadko płaczesz i często się śmiejesz',
    },

    {
      type: 'single-choice',
      question: 'płakać',
      choices: [
        'hauska',
        ' tanssin',
        ' paljon',
        ' harvoin',
        ' rehellinen',
        ' millainen',
        ' teillä',
      ],
      correctAnswer: 'harvoin',
    },

    {
      type: 'create-sentence',
      question: 'Missä kaupunki on?',
      choices: [
        'Meillä',
        ' Terve',
        ' Missä',
        ' te',
        ' ja',
        ' on',
        ' kiltti',
        ' kaupunki',
        ' kissa',
      ],
      correctAnswer: 'Gdzie jest miasto',
    },

    {
      type: 'single-choice',
      question: 'Gdzie',
      choices: [
        'tämä',
        ' minä',
        ' fin',
        ' missä',
        ' viro',
        ' millainen',
        ' nainen',
      ],
      correctAnswer: 'missä',
    },

    {
      type: 'create-sentence',
      question: 'Piękna piosenka jest rosyjska ',
      choices: [
        'laulu',
        ' lapsi',
        ' viro',
        ' Ruotsi',
        ' Kaunis',
        ' to',
        ' on',
        ' venäläinen',
        ' mies',
      ],
      correctAnswer: 'Kaunis laulu on venäläinen',
    },

    {
      type: 'create-sentence',
      question: 'Kaunis laulu on venäläinen',
      choices: [
        'kot',
        ' jest',
        ' szwecja',
        ' tańcze',
        ' Miła',
        ' rosyjska',
        ' piosenka',
        ' Piękna',
        ' też ',
      ],
      correctAnswer: 'Piękna piosenka jest rosyjska',
    },

    {
      type: 'single-choice',
      question: 'venäläinen',
      choices: [
        'rosyjska',
        ' Szwecja',
        ' dziewczyna',
        ' pierwszy',
        ' wiem',
        ' brązowy',
        ' rzadko',
      ],
      correctAnswer: 'rosyjska',
    },

    {
      type: 'create-sentence',
      question: 'Oletteko te nyt pari?',
      choices: [
        'Powodzenia',
        ' i',
        ' Przepraszam',
        ' zawsze',
        ' teraz',
        ' parą',
        ' Jesteście',
        ' Jesteśmy',
      ],
      correctAnswer: 'Jesteście teraz parą',
    },

    {
      type: 'single-choice',
      question: 'teraz',
      choices: [
        'pari',
        ' talo',
        ' yhdessä',
        ' usein ',
        'istuvat',
        ' olen',
        ' olemee',
        ' lapsi',
        ' nyt',
      ],
      correctAnswer: 'nyt',
    },

    {
      type: 'create-sentence',
      question: 'Ja tańcze',
      choices: [
        'Sinä',
        ' ja ',
        ' ma',
        ' aina',
        ' tanssin',
        ' maa',
        ' Meillä',
        ' Minä',
        ' Pyry',
        ' millainen',
      ],
      correctAnswer: 'Minä tanssin',
    },

    {
      type: 'single-choice',
      question: 'tanssin',
      choices: [
        'teraz',
        ' używać',
        ' tygrys',
        ' jutro',
        ' tańczyć',
        ' telewizja',
        ' zabawny',
      ],
      correctAnswer: 'tańczyć',
    },

    {
      type: 'create-sentence',
      question: 'Me olemme naimisissa',
      choices: [
        'Teraz',
        ' kaunis',
        ' małżeństwem',
        ' lubie',
        ' robie',
        ' fikołka',
        ' Jesteśmy',
        ' Też',
      ],
      correctAnswer: 'Jesteśmy małżeństwem',
    },

    {
      type: 'create-sentence',
      question: 'He istuvat yhdessä',
      choices: [
        'On',
        ' Ty',
        ' siedzisz',
        ' sam',
        ' parą',
        ' razem',
        ' są',
        ' Oni',
        ' siedzą',
        ' radio',
      ],
      correctAnswer: 'Oni siedzą razem',
    },

    {
      type: 'single-choice',
      question: 'istuvat',
      choices: [
        'tańczyć',
        ' pies',
        ' kot',
        ' kobieta',
        ' robić',
        ' siedzą',
        ' gotować',
      ],
      correctAnswer: 'siedzą',
    },

    {
      type: 'create-sentence',
      question: 'Oni siedzą razem',
      choices: [
        'Sinä',
        ' Olet',
        ' itket',
        ' istuvat',
        ' He',
        ' rehellinen',
        ' yhdessä',
        ' usein',
      ],
      correctAnswer: 'He istuvat yhdessä',
    },

    {
      type: 'create-sentence',
      question: 'Missä te seisotte?',
      choices: [
        'Co',
        ' Jak',
        ' robisz',
        ' tańczysz',
        ' siedzisz',
        ' Kim',
        ' jesteś',
        ' Gdzie',
        ' stoisz',
      ],
      correctAnswer: 'Gdzie stoisz',
    },

    {
      type: 'create-sentence',
      question: 'Ty rzadko płaczesz i często się śmiejesz',
      choices: [
        'usein',
        ' Ja',
        ' itket',
        ' Minulla',
        ' pari',
        ' aina',
        ' Sinä',
        ' fin',
        ' ja',
        ' to',
        ' harvoin',
        ' naurat',
      ],
      correctAnswer: 'Sinä itket harvoin ja naurat usein',
    },

    {
      type: 'create-sentence',
      question: 'Sinä itket harvoin ja naurat usein',
      choices: [
        'My',
        ' często',
        ' tańczymy',
        ' i',
        ' nie',
        ' używamy',
        ' Ty',
        ' rzadko',
        ' śmiejesz',
        ' się',
        ' płaczesz',
      ],
      correctAnswer: 'Ty rzadko płaczesz i często się śmiejesz',
    },

    {
      type: 'single-choice',
      question: 'płakać',
      choices: [
        'hauska',
        ' tanssin',
        ' paljon',
        ' harvoin',
        ' rehellinen',
        ' millainen',
        ' teillä',
      ],
      correctAnswer: 'harvoin',
    },

    {
      type: 'create-sentence',
      question: 'Minulla on uusi lelu',
      choices: [
        'Masz',
        ' radio',
        ' zajączka',
        ' starą',
        ' nową',
        ' Mam',
        ' zabawke',
        ' Ona',
        ' ma',
      ],
      correctAnswer: 'Mam nową zabawke',
    },

    {
      type: 'single-choice',
      question: 'uusi',
      choices: [
        'teraz',
        ' piękny',
        ' mały',
        ' nowy',
        ' dom',
        ' starą',
        ' nowa',
      ],
      correctAnswer: 'nowa',
    },

    {
      type: 'create-sentence',
      question: 'Sinulla on kaunis talo',
      choices: [
        'Mamy',
        ' wiem',
        ' telewizja',
        ' Ty',
        ' piękne',
        ' dom',
        ' piękny',
        ' masz',
        ' My',
        ' kwiaty ',
      ],
      correctAnswer: 'Ty masz piękny dom',
    },

    {
      type: 'single-choice',
      question: 'talo',
      choices: [
        'to',
        ' razem',
        ' używamy',
        ' teraz',
        ' pies',
        ' tak',
        ' dom',
        ' dobra',
      ],
      correctAnswer: 'dom',
    },

    {
      type: 'create-sentence',
      question: 'Jaką masz saune?',
      choices: [
        'on',
        'tanssin',
        ' sauna',
        ' ja',
        ' Pari',
        ' Viro',
        ' Millainen',
        ' teillä',
        ' todella',
      ],
      correctAnswer: 'Millainen sauna teillä on',
    },

    {
      type: 'create-sentence',
      question: 'Millainen sauna teillä on?',
      choices: [
        'tak',
        ' Jutro',
        ' jest',
        ' Gdzie',
        ' Jaką',
        ' saune',
        ' mamy',
        ' mała',
        ' masz',
        ' Którą',
      ],
      correctAnswer: 'Jaką masz saune',
    },

    {
      type: 'create-sentence',
      question: 'My mamy dużą saune',
      choices: [
        'Meillä',
        ' lapsi',
        ' sinä',
        ' sauna',
        ' paljon',
        ' pari',
        ' on',
        ' aina',
        ' suuri',
        ' laulu',
      ],
      correctAnswer: 'Meillä on suuri sauna',
    },

    {
      type: 'create-sentence',
      question: 'Meillä on suuri sauna',
      choices: [
        'Wy',
        ' macie',
        ' mamy',
        ' saune',
        ' waszą',
        ' mamy',
        ' piękną',
        ' szczery',
        ' dużą',
        ' My',
      ],
      correctAnswer: 'My mamy dużą saune',
    },

    {
      type: 'create-sentence',
      question: 'Heillä on radio ja televisio',
      choices: [
        'i',
        ' Oni',
        ' lubie',
        ' Ja',
        ' Wy',
        ' radio',
        ' telewizje',
        ' psa',
        ' siedzą',
        ' mają',
        ' mam',
      ],
      correctAnswer: 'Oni mają radio i telewizje',
    },

    {
      type: 'create-sentence',
      question: 'Kaunis laulu on venäläinen',
      choices: [
        'kot',
        ' jest',
        ' szwecja',
        ' tańcze',
        ' Miła',
        ' rosyjska',
        ' piosenka',
        ' Piękna',
        ' też ',
      ],
      correctAnswer: 'Piękna piosenka jest rosyjska',
    },

    {
      type: 'single-choice',
      question: 'venäläinen',
      choices: [
        'rosyjska',
        ' Szwecja',
        ' dziewczyna',
        ' pierwszy',
        ' wiem',
        ' brązowy',
        ' rzadko',
      ],
      correctAnswer: 'rosyjska',
    },

    {
      type: 'create-sentence',
      question: 'Ty rzadko płaczesz i często się śmiejesz',
      choices: [
        'usein',
        ' Ja',
        ' itket',
        ' Minulla',
        ' pari',
        ' aina',
        ' Sinä',
        ' fin',
        ' ja',
        ' to',
        ' harvoin',
        ' naurat',
      ],
      correctAnswer: 'Sinä itket harvoin ja naurat usein',
    },

    {
      type: 'create-sentence',
      question: 'Missä kaupunki on?',
      choices: [
        'Meillä',
        ' Terve',
        ' Missä',
        ' te',
        ' ja',
        ' on',
        ' kiltti',
        ' kaupunki',
        ' kissa',
      ],
      correctAnswer: 'Gdzie jest miasto',
    },

    {
      type: 'single-choice',
      question: 'Gdzie',
      choices: [
        'tämä',
        ' minä',
        ' fin',
        ' missä',
        ' viro',
        ' millainen',
        ' nainen',
      ],
      correctAnswer: 'missä',
    },

    {
      type: 'create-sentence',
      question: 'Millainen sauna teillä on?',
      choices: [
        'tak',
        ' Jutro',
        ' jest',
        ' Gdzie',
        ' Jaką',
        ' saune',
        ' mamy',
        ' mała',
        ' masz',
        ' Którą',
      ],
      correctAnswer: 'Jaką masz saune',
    },

    {
      type: 'single-choice',
      question: 'uusi',
      choices: [
        'teraz',
        ' piękny',
        ' mały',
        ' nowy',
        ' dom',
        ' starą',
        ' nowa',
      ],
      correctAnswer: 'nowa',
    },

    {
      type: 'single-choice',
      question: 'talo',
      choices: [
        'to',
        ' razem',
        ' używamy',
        ' teraz',
        ' pies',
        ' tak',
        ' dom',
        ' dobra',
      ],
      correctAnswer: 'dom',
    },

    {
      type: 'create-sentence',
      question: 'Sinulla on kaunis talo',
      choices: [
        'Mamy',
        ' wiem',
        ' telewizja',
        ' Ty',
        ' piękne',
        ' dom',
        ' piękny',
        ' masz',
        ' My',
        ' kwiaty ',
      ],
      correctAnswer: 'Ty masz piękny dom',
    },

    {
      type: 'create-sentence',
      question: 'Sinä itket harvoin ja naurat usein',
      choices: [
        'My',
        ' często',
        ' tańczymy',
        ' i',
        ' nie',
        ' używamy',
        ' Ty',
        ' rzadko',
        ' śmiejesz',
        ' się',
        ' płaczesz',
      ],
      correctAnswer: 'Ty rzadko płaczesz i często się śmiejesz',
    },

    {
      type: 'single-choice',
      question: 'płakać',
      choices: [
        'hauska',
        ' tanssin',
        ' paljon',
        ' harvoin',
        ' rehellinen',
        ' millainen',
        ' teillä',
      ],
      correctAnswer: 'harvoin',
    },

    {
      type: 'create-sentence',
      question: 'Missä kaupunki on?',
      choices: [
        'Meillä',
        ' Terve',
        ' Missä',
        ' te',
        ' ja',
        ' on',
        ' kiltti',
        ' kaupunki',
        ' kissa',
      ],
      correctAnswer: 'Gdzie jest miasto',
    },

    {
      type: 'single-choice',
      question: 'Gdzie',
      choices: [
        'tämä',
        ' minä',
        ' fin',
        ' missä',
        ' viro',
        ' millainen',
        ' nainen',
      ],
      correctAnswer: 'missä',
    },

    {
      type: 'create-sentence',
      question: 'Piękna piosenka jest rosyjska ',
      choices: [
        'laulu',
        ' lapsi',
        ' viro',
        ' Ruotsi',
        ' Kaunis',
        ' to',
        ' on',
        ' venäläinen',
        ' mies',
      ],
      correctAnswer: 'Kaunis laulu on venäläinen',
    },

    {
      type: 'create-sentence',
      question: 'Kaunis laulu on venäläinen',
      choices: [
        'kot',
        ' jest',
        ' szwecja',
        ' tańcze',
        ' Miła',
        ' rosyjska',
        ' piosenka',
        ' Piękna',
        ' też ',
      ],
      correctAnswer: 'Piękna piosenka jest rosyjska',
    },

    {
      type: 'single-choice',
      question: 'venäläinen',
      choices: [
        'rosyjska',
        ' Szwecja',
        ' dziewczyna',
        ' pierwszy',
        ' wiem',
        ' brązowy',
        ' rzadko',
      ],
      correctAnswer: 'rosyjska',
    },

    {
      type: 'create-sentence',
      question: 'Oletteko te nyt pari?',
      choices: [
        'Powodzenia',
        ' i',
        ' Przepraszam',
        ' zawsze',
        ' teraz',
        ' parą',
        ' Jesteście',
        ' Jesteśmy',
      ],
      correctAnswer: 'Jesteście teraz parą',
    },

    {
      type: 'single-choice',
      question: 'teraz',
      choices: [
        'pari',
        ' talo',
        ' yhdessä',
        ' usein ',
        'istuvat',
        ' olen',
        ' olemee',
        ' lapsi',
        ' nyt',
      ],
      correctAnswer: 'nyt',
    },

    {
      type: 'create-sentence',
      question: 'Ja tańcze',
      choices: [
        'Sinä',
        ' ja ',
        ' ma',
        ' aina',
        ' tanssin',
        ' maa',
        ' Meillä',
        ' Minä',
        ' Pyry',
        ' millainen',
      ],
      correctAnswer: 'Minä tanssin',
    },

    {
      type: 'single-choice',
      question: 'tanssin',
      choices: [
        'teraz',
        ' używać',
        ' tygrys',
        ' jutro',
        ' tańczyć',
        ' telewizja',
        ' zabawny',
      ],
      correctAnswer: 'tańczyć',
    },

    {
      type: 'create-sentence',
      question: 'Me olemme naimisissa',
      choices: [
        'Teraz',
        ' kaunis',
        ' małżeństwem',
        ' lubie',
        ' robie',
        ' fikołka',
        ' Jesteśmy',
        ' Też',
      ],
      correctAnswer: 'Jesteśmy małżeństwem',
    },

    {
      type: 'create-sentence',
      question: 'He istuvat yhdessä',
      choices: [
        'On',
        ' Ty',
        ' siedzisz',
        ' sam',
        ' parą',
        ' razem',
        ' są',
        ' Oni',
        ' siedzą',
        ' radio',
      ],
      correctAnswer: 'Oni siedzą razem',
    },

    {
      type: 'single-choice',
      question: 'istuvat',
      choices: [
        'tańczyć',
        ' pies',
        ' kot',
        ' kobieta',
        ' robić',
        ' siedzą',
        ' gotować',
      ],
      correctAnswer: 'siedzą',
    },

    {
      type: 'create-sentence',
      question: 'Oni siedzą razem',
      choices: [
        'Sinä',
        ' Olet',
        ' itket',
        ' istuvat',
        ' He',
        ' rehellinen',
        ' yhdessä',
        ' usein',
      ],
      correctAnswer: 'He istuvat yhdessä',
    },

    {
      type: 'create-sentence',
      question: 'Missä te seisotte?',
      choices: [
        'Co',
        ' Jak',
        ' robisz',
        ' tańczysz',
        ' siedzisz',
        ' Kim',
        ' jesteś',
        ' Gdzie',
        ' stoisz',
      ],
      correctAnswer: 'Gdzie stoisz',
    },

    {
      type: 'create-sentence',
      question: 'Ty rzadko płaczesz i często się śmiejesz',
      choices: [
        'usein',
        ' Ja',
        ' itket',
        ' Minulla',
        ' pari',
        ' aina',
        ' Sinä',
        ' fin',
        ' ja',
        ' to',
        ' harvoin',
        ' naurat',
      ],
      correctAnswer: 'Sinä itket harvoin ja naurat usein',
    },

    {
      type: 'create-sentence',
      question: 'Sinä itket harvoin ja naurat usein',
      choices: [
        'My',
        ' często',
        ' tańczymy',
        ' i',
        ' nie',
        ' używamy',
        ' Ty',
        ' rzadko',
        ' śmiejesz',
        ' się',
        ' płaczesz',
      ],
      correctAnswer: 'Ty rzadko płaczesz i często się śmiejesz',
    },

    {
      type: 'single-choice',
      question: 'płakać',
      choices: [
        'hauska',
        ' tanssin',
        ' paljon',
        ' harvoin',
        ' rehellinen',
        ' millainen',
        ' teillä',
      ],
      correctAnswer: 'harvoin',
    },

    {
      type: 'create-sentence',
      question: 'Minulla on uusi lelu',
      choices: [
        'Masz',
        ' radio',
        ' zajączka',
        ' starą',
        ' nową',
        ' Mam',
        ' zabawke',
        ' Ona',
        ' ma',
      ],
      correctAnswer: 'Mam nową zabawke',
    },

    {
      type: 'single-choice',
      question: 'uusi',
      choices: [
        'teraz',
        ' piękny',
        ' mały',
        ' nowy',
        ' dom',
        ' starą',
        ' nowa',
      ],
      correctAnswer: 'nowa',
    },

    {
      type: 'create-sentence',
      question: 'Sinulla on kaunis talo',
      choices: [
        'Mamy',
        ' wiem',
        ' telewizja',
        ' Ty',
        ' piękne',
        ' dom',
        ' piękny',
        ' masz',
        ' My',
        ' kwiaty ',
      ],
      correctAnswer: 'Ty masz piękny dom',
    },

    {
      type: 'single-choice',
      question: 'talo',
      choices: [
        'to',
        ' razem',
        ' używamy',
        ' teraz',
        ' pies',
        ' tak',
        ' dom',
        ' dobra',
      ],
      correctAnswer: 'dom',
    },

    {
      type: 'create-sentence',
      question: 'Jaką masz saune?',
      choices: [
        'on',
        'tanssin',
        ' sauna',
        ' ja',
        ' Pari',
        ' Viro',
        ' Millainen',
        ' teillä',
        ' todella',
      ],
      correctAnswer: 'Millainen sauna teillä on',
    },

    {
      type: 'create-sentence',
      question: 'Millainen sauna teillä on?',
      choices: [
        'tak',
        ' Jutro',
        ' jest',
        ' Gdzie',
        ' Jaką',
        ' saune',
        ' mamy',
        ' mała',
        ' masz',
        ' Którą',
      ],
      correctAnswer: 'Jaką masz saune',
    },

    {
      type: 'create-sentence',
      question: 'My mamy dużą saune',
      choices: [
        'Meillä',
        ' lapsi',
        ' sinä',
        ' sauna',
        ' paljon',
        ' pari',
        ' on',
        ' aina',
        ' suuri',
        ' laulu',
      ],
      correctAnswer: 'Meillä on suuri sauna',
    },

    {
      type: 'create-sentence',
      question: 'Meillä on suuri sauna',
      choices: [
        'Wy',
        ' macie',
        ' mamy',
        ' saune',
        ' waszą',
        ' mamy',
        ' piękną',
        ' szczery',
        ' dużą',
        ' My',
      ],
      correctAnswer: 'My mamy dużą saune',
    },

    {
      type: 'create-sentence',
      question: 'Heillä on radio ja televisio',
      choices: [
        'i',
        ' Oni',
        ' lubie',
        ' Ja',
        ' Wy',
        ' radio',
        ' telewizje',
        ' psa',
        ' siedzą',
        ' mają',
        ' mam',
      ],
      correctAnswer: 'Oni mają radio i telewizje',
    },

    {
      type: 'create-sentence',
      question: 'Kaunis laulu on venäläinen',
      choices: [
        'kot',
        ' jest',
        ' szwecja',
        ' tańcze',
        ' Miła',
        ' rosyjska',
        ' piosenka',
        ' Piękna',
        ' też ',
      ],
      correctAnswer: 'Piękna piosenka jest rosyjska',
    },

    {
      type: 'single-choice',
      question: 'venäläinen',
      choices: [
        'rosyjska',
        ' Szwecja',
        ' dziewczyna',
        ' pierwszy',
        ' wiem',
        ' brązowy',
        ' rzadko',
      ],
      correctAnswer: 'rosyjska',
    },

    {
      type: 'create-sentence',
      question: 'Ty rzadko płaczesz i często się śmiejesz',
      choices: [
        'usein',
        ' Ja',
        ' itket',
        ' Minulla',
        ' pari',
        ' aina',
        ' Sinä',
        ' fin',
        ' ja',
        ' to',
        ' harvoin',
        ' naurat',
      ],
      correctAnswer: 'Sinä itket harvoin ja naurat usein',
    },

    {
      type: 'create-sentence',
      question: 'Missä kaupunki on?',
      choices: [
        'Meillä',
        ' Terve',
        ' Missä',
        ' te',
        ' ja',
        ' on',
        ' kiltti',
        ' kaupunki',
        ' kissa',
      ],
      correctAnswer: 'Gdzie jest miasto',
    },

    {
      type: 'single-choice',
      question: 'Gdzie',
      choices: [
        'tämä',
        ' minä',
        ' fin',
        ' missä',
        ' viro',
        ' millainen',
        ' nainen',
      ],
      correctAnswer: 'missä',
    },

    {
      type: 'create-sentence',
      question: 'Millainen sauna teillä on?',
      choices: [
        'tak',
        ' Jutro',
        ' jest',
        ' Gdzie',
        ' Jaką',
        ' saune',
        ' mamy',
        ' mała',
        ' masz',
        ' Którą',
      ],
      correctAnswer: 'Jaką masz saune',
    },

    {
      type: 'single-choice',
      question: 'uusi',
      choices: [
        'teraz',
        ' piękny',
        ' mały',
        ' nowy',
        ' dom',
        ' starą',
        ' nowa',
      ],
      correctAnswer: 'nowa',
    },

    {
      type: 'single-choice',
      question: 'talo',
      choices: [
        'to',
        ' razem',
        ' używamy',
        ' teraz',
        ' pies',
        ' tak',
        ' dom',
        ' dobra',
      ],
      correctAnswer: 'dom',
    },

    {
      type: 'create-sentence',
      question: 'Sinulla on kaunis talo',
      choices: [
        'Mamy',
        ' wiem',
        ' telewizja',
        ' Ty',
        ' piękne',
        ' dom',
        ' piękny',
        ' masz',
        ' My',
        ' kwiaty ',
      ],
      correctAnswer: 'Ty masz piękny dom',
    },

    {
      type: 'create-sentence',
      question: 'Sinä itket harvoin ja naurat usein',
      choices: [
        'My',
        ' często',
        ' tańczymy',
        ' i',
        ' nie',
        ' używamy',
        ' Ty',
        ' rzadko',
        ' śmiejesz',
        ' się',
        ' płaczesz',
      ],
      correctAnswer: 'Ty rzadko płaczesz i często się śmiejesz',
    },

    {
      type: 'single-choice',
      question: 'płakać',
      choices: [
        'hauska',
        ' tanssin',
        ' paljon',
        ' harvoin',
        ' rehellinen',
        ' millainen',
        ' teillä',
      ],
      correctAnswer: 'harvoin',
    },
  ],
}

export const banners = {
  QuizOne: {
    top: [],

    right: [],

    left: [],
  },

  QuizTwo: {
    top: ['media/TwoTop/banner.png', 'media/TwoTop/widestjigglin.webp'],

    right: ['media/TwoSide/crunch-cat.gif', 'media/TwoSide/widetime.gif'],

    left: ['media/TwoSide/crunch-cat.gif', 'media/TwoSide/widetime.gif'],
  },
  QuizThree: {
    top: [],

    right: [],

    left: [],
  },
}

export const resultInitialState = {
  score: 0,
  correctAnswers: 0,
  wrongAnswers: 0,
}
